<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Using MRMCaov for R</title>

<script src="site_libs/header-attrs-2.19/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="../src/style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">MRMCaov for R</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="using.html">Using</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/brian-j-smith/MRMCaov">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Using MRMCaov for R</h1>
<h3 class="subtitle">Package Version 0.3.0</h3>

</div>


<div id="introduction" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>A common study design for comparing the diagnostic performance of
imaging modalities, or diagnostic tests, is to obtain modality-specific
ratings from multiple readers of multiple cases (MRMC) whose true
statuses are known. In such a design, receiver operating characteristic
(ROC) indices, such as area under the ROC curve (ROC AUC), can be used
to quantify correspondence between reader ratings and case status.
Indices can then be compared statistically to determine if there are
differences between modalities. However, special statistical methods are
needed when readers or cases represent a random sample from a larger
population of interest and there is overlap between modalities, readers,
and/or cases. An ANOVA model designed for these characteristics of MRMC
studies was initially proposed by Dorfman et al. <span
class="citation">(Dorfman, Berbaum, and Metz 1992)</span> and Obuchowski
and Rockette <span class="citation">(Obuchowski and Rockette
1995)</span> and later unified and improved by Hillis and colleagues
<span class="citation">(Hillis et al. 2005; Hillis 2007, 2018; Hillis,
Berbaum, and Metz 2008)</span>. Their models are implemented in the
<strong>MRMCaov</strong> R package <span class="citation">(Brian J.
Smith, Hillis, and Pesce 2022)</span>.</p>
</div>
<div id="obuchowski-and-rockette-model" class="section level1"
number="2">
<h1><span class="header-section-number">2</span> Obuchowski and Rockette
Model</h1>
<p><strong>MRMCaov</strong> implements multi-reader multi-case analysis
based on the Obuchowski and Rockette <span
class="citation">(1995)</span> analysis of variance (ANOVA) model <span
class="math display">\[
\hat{\theta}_{ij} = \mu + \tau_i + R_j + (\tau R)_{ij} + \epsilon_{ij},
\]</span> where <span class="math inline">\(i = 1,\ldots,t\)</span> and
<span class="math inline">\(j = 1,\ldots,r\)</span> index diagnostic
tests and readers; <span
class="math inline">\(\hat{\theta}_{ij}\)</span> is a reader performance
metric, such as ROC AUC, estimated over multiple cases; <span
class="math inline">\(\mu\)</span> an overall study mean; <span
class="math inline">\(\tau_i\)</span> a fixed test effect; <span
class="math inline">\(R_j\)</span> a random reader effect; <span
class="math inline">\((\tau R)_{ij}\)</span> a random test <span
class="math inline">\(\times\)</span> reader interaction effect; and
<span class="math inline">\(\epsilon_{ij}\)</span> a random error term.
The random terms <span class="math inline">\(R_j\)</span>, <span
class="math inline">\((\tau R)_{ij}\)</span>, and <span
class="math inline">\(\epsilon_{ij}\)</span> are assumed to be mutually
independent and normally distributed with 0 means and variances <span
class="math inline">\(\sigma^2_R\)</span>, <span
class="math inline">\(\sigma^2_{TR}\)</span>, and <span
class="math inline">\(\sigma^2_\epsilon\)</span>.</p>
<p>The error covariances between tests and between readers are further
assumed to be equal, resulting in the three covariances <span
class="math display">\[
\text{Cov}(\epsilon_{ij}, \epsilon_{i&#39;j&#39;}) = \left\{
  \begin{array}{lll}
    \text{Cov}_1 &amp; i \ne i&#39;, j = j&#39; &amp; \text{(different
test, same reader)} \\
    \text{Cov}_2 &amp; i = i&#39;, j \ne j&#39; &amp; \text{(same test,
same reader)} \\
    \text{Cov}_3 &amp; i \ne i&#39;, j \ne j&#39; &amp; \text{(different
test, different reader)}.
  \end{array}
\right.
\]</span> Obuchowski and Rockette <span class="citation">(1995)</span>
suggest a covariance ordering of <span
class="math inline">\(\text{Cov}_1 \ge \text{Cov}_2 \ge \text{Cov}_3 \ge
0\)</span> based on clinical considerations. Hillis <span
class="citation">(2014)</span> later showed that these can be replaced
with the less restrictive orderings <span
class="math inline">\(\text{Cov}_1 \ge \text{Cov}_3\)</span>, <span
class="math inline">\(\text{Cov}_2 \ge \text{Cov}_3\)</span>, and <span
class="math inline">\(\text{Cov}_3 \ge 0\)</span>. Alternatively, the
covariance can be specified as the population correlations <span
class="math inline">\(\rho_i = \text{Cov}_i /
\sigma^2_\epsilon\)</span>.</p>
<p>In the Obuchowski-Rockette ANOVA model, <span
class="math inline">\(\sigma^2_\epsilon\)</span> can be interpreted as
the performance metric variance for a single fixed reader and test; and
<span class="math inline">\(\text{Cov}_1\)</span>, <span
class="math inline">\(\text{Cov}_2\)</span>, and <span
class="math inline">\(\text{Cov}_3\)</span> as the performance metric
covariances for the same reader of two different tests, two different
readers of the same test, and two different readers of two different
tests. These error variance and covariance parameters are estimated in
the package by averaging the reader and test-specific estimates computed
using jackknifing <span class="citation">(Efron 1982)</span> or, for
empirical ROC AUC, an unbiased estimator <span class="citation">(Gallas,
Pennello, and Meyers 2007)</span> or the method of DeLong <span
class="citation">(DeLong, DeLong, and Clarke-Pearson 1988)</span>.</p>
</div>
<div id="vandyke-example" class="section level1" number="3">
<h1><span class="header-section-number">3</span> VanDyke Example</h1>
<p>Use of the <strong>MRMCaov</strong> package is illustrated with data
from a study comparing the relative performance of cinematic
presentation of MRI (CINE MRI) to single spin-echo magnetic resonance
imaging (SE MRI) for the detection of thoracic aortic dissection <span
class="citation">(VanDyke et al. 1993)</span>. In the study, 45 patients
with aortic dissection and 69 without dissection were imaged with both
modalities. Based on the images, five radiologists rated patients
disease statuses as 1 = definitely no aortic dissection, 2 = probably no
aortic dissection, 3 = unsure about aortic dissection, 4 = probably
aortic dissection, or 5 = definitely aortic dissection. Interest lies in
estimating ROC curves for each combination of reader and modality and in
comparing modalities with respect to summary statistics from the curves.
The study data are included in the package as a data frame named
<code>VanDyke</code>.</p>
<pre class="r"><code>## Load MRMCaov library and VanDyke dataset
library(MRMCaov)
data(VanDyke, package = &quot;MRMCaov&quot;)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["reader"],"name":[1],"type":["fct"],"align":["left"]},{"label":["treatment"],"name":[2],"type":["fct"],"align":["left"]},{"label":["case"],"name":[3],"type":["fct"],"align":["left"]},{"label":["truth"],"name":[4],"type":["int"],"align":["right"]},{"label":["rating"],"name":[5],"type":["int"],"align":["right"]},{"label":["case2"],"name":[6],"type":["fct"],"align":["left"]},{"label":["case3"],"name":[7],"type":["fct"],"align":["left"]}],"data":[{"1":"1","2":"1","3":"1","4":"0","5":"1","6":"1.1","7":"1.1"},{"1":"1","2":"2","3":"1","4":"0","5":"3","6":"1.1","7":"2.1"},{"1":"2","2":"1","3":"1","4":"0","5":"2","6":"2.1","7":"1.1"},{"1":"2","2":"2","3":"1","4":"0","5":"3","6":"2.1","7":"2.1"},{"1":"3","2":"1","3":"1","4":"0","5":"2","6":"3.1","7":"1.1"},{"1":"3","2":"2","3":"1","4":"0","5":"2","6":"3.1","7":"2.1"},{"1":"4","2":"1","3":"1","4":"0","5":"1","6":"4.1","7":"1.1"},{"1":"4","2":"2","3":"1","4":"0","5":"2","6":"4.1","7":"2.1"},{"1":"5","2":"1","3":"1","4":"0","5":"3","6":"5.1","7":"1.1"},{"1":"5","2":"2","3":"1","4":"0","5":"2","6":"5.1","7":"2.1"},{"1":"1","2":"1","3":"2","4":"0","5":"2","6":"1.2","7":"1.2"},{"1":"1","2":"2","3":"2","4":"0","5":"3","6":"1.2","7":"2.2"},{"1":"2","2":"1","3":"2","4":"0","5":"3","6":"2.2","7":"1.2"},{"1":"2","2":"2","3":"2","4":"0","5":"2","6":"2.2","7":"2.2"},{"1":"3","2":"1","3":"2","4":"0","5":"2","6":"3.2","7":"1.2"},{"1":"3","2":"2","3":"2","4":"0","5":"4","6":"3.2","7":"2.2"},{"1":"4","2":"1","3":"2","4":"0","5":"1","6":"4.2","7":"1.2"},{"1":"4","2":"2","3":"2","4":"0","5":"2","6":"4.2","7":"2.2"},{"1":"5","2":"1","3":"2","4":"0","5":"5","6":"5.2","7":"1.2"},{"1":"5","2":"2","3":"2","4":"0","5":"2","6":"5.2","7":"2.2"},{"1":"1","2":"1","3":"3","4":"0","5":"2","6":"1.3","7":"1.3"},{"1":"1","2":"2","3":"3","4":"0","5":"3","6":"1.3","7":"2.3"},{"1":"2","2":"1","3":"3","4":"0","5":"2","6":"2.3","7":"1.3"},{"1":"2","2":"2","3":"3","4":"0","5":"2","6":"2.3","7":"2.3"},{"1":"3","2":"1","3":"3","4":"0","5":"2","6":"3.3","7":"1.3"},{"1":"3","2":"2","3":"3","4":"0","5":"2","6":"3.3","7":"2.3"},{"1":"4","2":"1","3":"3","4":"0","5":"1","6":"4.3","7":"1.3"},{"1":"4","2":"2","3":"3","4":"0","5":"1","6":"4.3","7":"2.3"},{"1":"5","2":"1","3":"3","4":"0","5":"1","6":"5.3","7":"1.3"},{"1":"5","2":"2","3":"3","4":"0","5":"3","6":"5.3","7":"2.3"},{"1":"1","2":"1","3":"4","4":"0","5":"1","6":"1.4","7":"1.4"},{"1":"1","2":"2","3":"4","4":"0","5":"2","6":"1.4","7":"2.4"},{"1":"2","2":"1","3":"4","4":"0","5":"2","6":"2.4","7":"1.4"},{"1":"2","2":"2","3":"4","4":"0","5":"2","6":"2.4","7":"2.4"},{"1":"3","2":"1","3":"4","4":"0","5":"2","6":"3.4","7":"1.4"},{"1":"3","2":"2","3":"4","4":"0","5":"2","6":"3.4","7":"2.4"},{"1":"4","2":"1","3":"4","4":"0","5":"1","6":"4.4","7":"1.4"},{"1":"4","2":"2","3":"4","4":"0","5":"1","6":"4.4","7":"2.4"},{"1":"5","2":"1","3":"4","4":"0","5":"2","6":"5.4","7":"1.4"},{"1":"5","2":"2","3":"4","4":"0","5":"1","6":"5.4","7":"2.4"},{"1":"1","2":"1","3":"5","4":"0","5":"5","6":"1.5","7":"1.5"},{"1":"1","2":"2","3":"5","4":"0","5":"2","6":"1.5","7":"2.5"},{"1":"2","2":"1","3":"5","4":"0","5":"2","6":"2.5","7":"1.5"},{"1":"2","2":"2","3":"5","4":"0","5":"2","6":"2.5","7":"2.5"},{"1":"3","2":"1","3":"5","4":"0","5":"3","6":"3.5","7":"1.5"},{"1":"3","2":"2","3":"5","4":"0","5":"2","6":"3.5","7":"2.5"},{"1":"4","2":"1","3":"5","4":"0","5":"1","6":"4.5","7":"1.5"},{"1":"4","2":"2","3":"5","4":"0","5":"1","6":"4.5","7":"2.5"},{"1":"5","2":"1","3":"5","4":"0","5":"1","6":"5.5","7":"1.5"},{"1":"5","2":"2","3":"5","4":"0","5":"2","6":"5.5","7":"2.5"},{"1":"1","2":"1","3":"6","4":"0","5":"1","6":"1.6","7":"1.6"},{"1":"1","2":"2","3":"6","4":"0","5":"2","6":"1.6","7":"2.6"},{"1":"2","2":"1","3":"6","4":"0","5":"2","6":"2.6","7":"1.6"},{"1":"2","2":"2","3":"6","4":"0","5":"2","6":"2.6","7":"2.6"},{"1":"3","2":"1","3":"6","4":"0","5":"5","6":"3.6","7":"1.6"},{"1":"3","2":"2","3":"6","4":"0","5":"2","6":"3.6","7":"2.6"},{"1":"4","2":"1","3":"6","4":"0","5":"1","6":"4.6","7":"1.6"},{"1":"4","2":"2","3":"6","4":"0","5":"1","6":"4.6","7":"2.6"},{"1":"5","2":"1","3":"6","4":"0","5":"1","6":"5.6","7":"1.6"},{"1":"5","2":"2","3":"6","4":"0","5":"2","6":"5.6","7":"2.6"},{"1":"1","2":"1","3":"7","4":"0","5":"1","6":"1.7","7":"1.7"},{"1":"1","2":"2","3":"7","4":"0","5":"2","6":"1.7","7":"2.7"},{"1":"2","2":"1","3":"7","4":"0","5":"2","6":"2.7","7":"1.7"},{"1":"2","2":"2","3":"7","4":"0","5":"2","6":"2.7","7":"2.7"},{"1":"3","2":"1","3":"7","4":"0","5":"1","6":"3.7","7":"1.7"},{"1":"3","2":"2","3":"7","4":"0","5":"3","6":"3.7","7":"2.7"},{"1":"4","2":"1","3":"7","4":"0","5":"3","6":"4.7","7":"1.7"},{"1":"4","2":"2","3":"7","4":"0","5":"3","6":"4.7","7":"2.7"},{"1":"5","2":"1","3":"7","4":"0","5":"1","6":"5.7","7":"1.7"},{"1":"5","2":"2","3":"7","4":"0","5":"2","6":"5.7","7":"2.7"},{"1":"1","2":"1","3":"8","4":"0","5":"1","6":"1.8","7":"1.8"},{"1":"1","2":"2","3":"8","4":"0","5":"2","6":"1.8","7":"2.8"},{"1":"2","2":"1","3":"8","4":"0","5":"2","6":"2.8","7":"1.8"},{"1":"2","2":"2","3":"8","4":"0","5":"2","6":"2.8","7":"2.8"},{"1":"3","2":"1","3":"8","4":"0","5":"1","6":"3.8","7":"1.8"},{"1":"3","2":"2","3":"8","4":"0","5":"2","6":"3.8","7":"2.8"},{"1":"4","2":"1","3":"8","4":"0","5":"1","6":"4.8","7":"1.8"},{"1":"4","2":"2","3":"8","4":"0","5":"1","6":"4.8","7":"2.8"},{"1":"5","2":"1","3":"8","4":"0","5":"1","6":"5.8","7":"1.8"},{"1":"5","2":"2","3":"8","4":"0","5":"2","6":"5.8","7":"2.8"},{"1":"1","2":"1","3":"9","4":"0","5":"1","6":"1.9","7":"1.9"},{"1":"1","2":"2","3":"9","4":"0","5":"3","6":"1.9","7":"2.9"},{"1":"2","2":"1","3":"9","4":"0","5":"2","6":"2.9","7":"1.9"},{"1":"2","2":"2","3":"9","4":"0","5":"3","6":"2.9","7":"2.9"},{"1":"3","2":"1","3":"9","4":"0","5":"2","6":"3.9","7":"1.9"},{"1":"3","2":"2","3":"9","4":"0","5":"2","6":"3.9","7":"2.9"},{"1":"4","2":"1","3":"9","4":"0","5":"1","6":"4.9","7":"1.9"},{"1":"4","2":"2","3":"9","4":"0","5":"2","6":"4.9","7":"2.9"},{"1":"5","2":"1","3":"9","4":"0","5":"2","6":"5.9","7":"1.9"},{"1":"5","2":"2","3":"9","4":"0","5":"1","6":"5.9","7":"2.9"},{"1":"1","2":"1","3":"10","4":"0","5":"1","6":"1.10","7":"1.10"},{"1":"1","2":"2","3":"10","4":"0","5":"2","6":"1.10","7":"2.10"},{"1":"2","2":"1","3":"10","4":"0","5":"3","6":"2.10","7":"1.10"},{"1":"2","2":"2","3":"10","4":"0","5":"2","6":"2.10","7":"2.10"},{"1":"3","2":"1","3":"10","4":"0","5":"2","6":"3.10","7":"1.10"},{"1":"3","2":"2","3":"10","4":"0","5":"2","6":"3.10","7":"2.10"},{"1":"4","2":"1","3":"10","4":"0","5":"1","6":"4.10","7":"1.10"},{"1":"4","2":"2","3":"10","4":"0","5":"1","6":"4.10","7":"2.10"},{"1":"5","2":"1","3":"10","4":"0","5":"2","6":"5.10","7":"1.10"},{"1":"5","2":"2","3":"10","4":"0","5":"2","6":"5.10","7":"2.10"},{"1":"1","2":"1","3":"11","4":"0","5":"1","6":"1.11","7":"1.11"},{"1":"1","2":"2","3":"11","4":"0","5":"1","6":"1.11","7":"2.11"},{"1":"2","2":"1","3":"11","4":"0","5":"2","6":"2.11","7":"1.11"},{"1":"2","2":"2","3":"11","4":"0","5":"2","6":"2.11","7":"2.11"},{"1":"3","2":"1","3":"11","4":"0","5":"4","6":"3.11","7":"1.11"},{"1":"3","2":"2","3":"11","4":"0","5":"1","6":"3.11","7":"2.11"},{"1":"4","2":"1","3":"11","4":"0","5":"1","6":"4.11","7":"1.11"},{"1":"4","2":"2","3":"11","4":"0","5":"1","6":"4.11","7":"2.11"},{"1":"5","2":"1","3":"11","4":"0","5":"2","6":"5.11","7":"1.11"},{"1":"5","2":"2","3":"11","4":"0","5":"2","6":"5.11","7":"2.11"},{"1":"1","2":"1","3":"12","4":"0","5":"1","6":"1.12","7":"1.12"},{"1":"1","2":"2","3":"12","4":"0","5":"3","6":"1.12","7":"2.12"},{"1":"2","2":"1","3":"12","4":"0","5":"2","6":"2.12","7":"1.12"},{"1":"2","2":"2","3":"12","4":"0","5":"2","6":"2.12","7":"2.12"},{"1":"3","2":"1","3":"12","4":"0","5":"2","6":"3.12","7":"1.12"},{"1":"3","2":"2","3":"12","4":"0","5":"1","6":"3.12","7":"2.12"},{"1":"4","2":"1","3":"12","4":"0","5":"1","6":"4.12","7":"1.12"},{"1":"4","2":"2","3":"12","4":"0","5":"1","6":"4.12","7":"2.12"},{"1":"5","2":"1","3":"12","4":"0","5":"1","6":"5.12","7":"1.12"},{"1":"5","2":"2","3":"12","4":"0","5":"2","6":"5.12","7":"2.12"},{"1":"1","2":"1","3":"13","4":"0","5":"4","6":"1.13","7":"1.13"},{"1":"1","2":"2","3":"13","4":"0","5":"1","6":"1.13","7":"2.13"},{"1":"2","2":"1","3":"13","4":"0","5":"5","6":"2.13","7":"1.13"},{"1":"2","2":"2","3":"13","4":"0","5":"2","6":"2.13","7":"2.13"},{"1":"3","2":"1","3":"13","4":"0","5":"4","6":"3.13","7":"1.13"},{"1":"3","2":"2","3":"13","4":"0","5":"1","6":"3.13","7":"2.13"},{"1":"4","2":"1","3":"13","4":"0","5":"1","6":"4.13","7":"1.13"},{"1":"4","2":"2","3":"13","4":"0","5":"1","6":"4.13","7":"2.13"},{"1":"5","2":"1","3":"13","4":"0","5":"2","6":"5.13","7":"1.13"},{"1":"5","2":"2","3":"13","4":"0","5":"1","6":"5.13","7":"2.13"},{"1":"1","2":"1","3":"14","4":"0","5":"1","6":"1.14","7":"1.14"},{"1":"1","2":"2","3":"14","4":"0","5":"2","6":"1.14","7":"2.14"},{"1":"2","2":"1","3":"14","4":"0","5":"2","6":"2.14","7":"1.14"},{"1":"2","2":"2","3":"14","4":"0","5":"2","6":"2.14","7":"2.14"},{"1":"3","2":"1","3":"14","4":"0","5":"2","6":"3.14","7":"1.14"},{"1":"3","2":"2","3":"14","4":"0","5":"3","6":"3.14","7":"2.14"},{"1":"4","2":"1","3":"14","4":"0","5":"1","6":"4.14","7":"1.14"},{"1":"4","2":"2","3":"14","4":"0","5":"2","6":"4.14","7":"2.14"},{"1":"5","2":"1","3":"14","4":"0","5":"1","6":"5.14","7":"1.14"},{"1":"5","2":"2","3":"14","4":"0","5":"1","6":"5.14","7":"2.14"},{"1":"1","2":"1","3":"15","4":"0","5":"1","6":"1.15","7":"1.15"},{"1":"1","2":"2","3":"15","4":"0","5":"2","6":"1.15","7":"2.15"},{"1":"2","2":"1","3":"15","4":"0","5":"2","6":"2.15","7":"1.15"},{"1":"2","2":"2","3":"15","4":"0","5":"2","6":"2.15","7":"2.15"},{"1":"3","2":"1","3":"15","4":"0","5":"2","6":"3.15","7":"1.15"},{"1":"3","2":"2","3":"15","4":"0","5":"2","6":"3.15","7":"2.15"},{"1":"4","2":"1","3":"15","4":"0","5":"1","6":"4.15","7":"1.15"},{"1":"4","2":"2","3":"15","4":"0","5":"2","6":"4.15","7":"2.15"},{"1":"5","2":"1","3":"15","4":"0","5":"1","6":"5.15","7":"1.15"},{"1":"5","2":"2","3":"15","4":"0","5":"1","6":"5.15","7":"2.15"},{"1":"1","2":"1","3":"16","4":"0","5":"1","6":"1.16","7":"1.16"},{"1":"1","2":"2","3":"16","4":"0","5":"2","6":"1.16","7":"2.16"},{"1":"2","2":"1","3":"16","4":"0","5":"2","6":"2.16","7":"1.16"},{"1":"2","2":"2","3":"16","4":"0","5":"1","6":"2.16","7":"2.16"},{"1":"3","2":"1","3":"16","4":"0","5":"2","6":"3.16","7":"1.16"},{"1":"3","2":"2","3":"16","4":"0","5":"2","6":"3.16","7":"2.16"},{"1":"4","2":"1","3":"16","4":"0","5":"1","6":"4.16","7":"1.16"},{"1":"4","2":"2","3":"16","4":"0","5":"1","6":"4.16","7":"2.16"},{"1":"5","2":"1","3":"16","4":"0","5":"1","6":"5.16","7":"1.16"},{"1":"5","2":"2","3":"16","4":"0","5":"2","6":"5.16","7":"2.16"},{"1":"1","2":"1","3":"17","4":"0","5":"1","6":"1.17","7":"1.17"},{"1":"1","2":"2","3":"17","4":"0","5":"2","6":"1.17","7":"2.17"},{"1":"2","2":"1","3":"17","4":"0","5":"3","6":"2.17","7":"1.17"},{"1":"2","2":"2","3":"17","4":"0","5":"2","6":"2.17","7":"2.17"},{"1":"3","2":"1","3":"17","4":"0","5":"3","6":"3.17","7":"1.17"},{"1":"3","2":"2","3":"17","4":"0","5":"2","6":"3.17","7":"2.17"},{"1":"4","2":"1","3":"17","4":"0","5":"1","6":"4.17","7":"1.17"},{"1":"4","2":"2","3":"17","4":"0","5":"1","6":"4.17","7":"2.17"},{"1":"5","2":"1","3":"17","4":"0","5":"2","6":"5.17","7":"1.17"},{"1":"5","2":"2","3":"17","4":"0","5":"2","6":"5.17","7":"2.17"},{"1":"1","2":"1","3":"18","4":"0","5":"1","6":"1.18","7":"1.18"},{"1":"1","2":"2","3":"18","4":"0","5":"2","6":"1.18","7":"2.18"},{"1":"2","2":"1","3":"18","4":"0","5":"2","6":"2.18","7":"1.18"},{"1":"2","2":"2","3":"18","4":"0","5":"2","6":"2.18","7":"2.18"},{"1":"3","2":"1","3":"18","4":"0","5":"2","6":"3.18","7":"1.18"},{"1":"3","2":"2","3":"18","4":"0","5":"2","6":"3.18","7":"2.18"},{"1":"4","2":"1","3":"18","4":"0","5":"1","6":"4.18","7":"1.18"},{"1":"4","2":"2","3":"18","4":"0","5":"1","6":"4.18","7":"2.18"},{"1":"5","2":"1","3":"18","4":"0","5":"2","6":"5.18","7":"1.18"},{"1":"5","2":"2","3":"18","4":"0","5":"2","6":"5.18","7":"2.18"},{"1":"1","2":"1","3":"19","4":"0","5":"1","6":"1.19","7":"1.19"},{"1":"1","2":"2","3":"19","4":"0","5":"2","6":"1.19","7":"2.19"},{"1":"2","2":"1","3":"19","4":"0","5":"2","6":"2.19","7":"1.19"},{"1":"2","2":"2","3":"19","4":"0","5":"2","6":"2.19","7":"2.19"},{"1":"3","2":"1","3":"19","4":"0","5":"2","6":"3.19","7":"1.19"},{"1":"3","2":"2","3":"19","4":"0","5":"1","6":"3.19","7":"2.19"},{"1":"4","2":"1","3":"19","4":"0","5":"1","6":"4.19","7":"1.19"},{"1":"4","2":"2","3":"19","4":"0","5":"2","6":"4.19","7":"2.19"},{"1":"5","2":"1","3":"19","4":"0","5":"1","6":"5.19","7":"1.19"},{"1":"5","2":"2","3":"19","4":"0","5":"1","6":"5.19","7":"2.19"},{"1":"1","2":"1","3":"20","4":"0","5":"1","6":"1.20","7":"1.20"},{"1":"1","2":"2","3":"20","4":"0","5":"1","6":"1.20","7":"2.20"},{"1":"2","2":"1","3":"20","4":"0","5":"2","6":"2.20","7":"1.20"},{"1":"2","2":"2","3":"20","4":"0","5":"2","6":"2.20","7":"2.20"},{"1":"3","2":"1","3":"20","4":"0","5":"2","6":"3.20","7":"1.20"},{"1":"3","2":"2","3":"20","4":"0","5":"2","6":"3.20","7":"2.20"},{"1":"4","2":"1","3":"20","4":"0","5":"1","6":"4.20","7":"1.20"},{"1":"4","2":"2","3":"20","4":"0","5":"1","6":"4.20","7":"2.20"},{"1":"5","2":"1","3":"20","4":"0","5":"1","6":"5.20","7":"1.20"},{"1":"5","2":"2","3":"20","4":"0","5":"2","6":"5.20","7":"2.20"},{"1":"1","2":"1","3":"21","4":"0","5":"1","6":"1.21","7":"1.21"},{"1":"1","2":"2","3":"21","4":"0","5":"1","6":"1.21","7":"2.21"},{"1":"2","2":"1","3":"21","4":"0","5":"2","6":"2.21","7":"1.21"},{"1":"2","2":"2","3":"21","4":"0","5":"1","6":"2.21","7":"2.21"},{"1":"3","2":"1","3":"21","4":"0","5":"1","6":"3.21","7":"1.21"},{"1":"3","2":"2","3":"21","4":"0","5":"1","6":"3.21","7":"2.21"},{"1":"4","2":"1","3":"21","4":"0","5":"2","6":"4.21","7":"1.21"},{"1":"4","2":"2","3":"21","4":"0","5":"1","6":"4.21","7":"2.21"},{"1":"5","2":"1","3":"21","4":"0","5":"3","6":"5.21","7":"1.21"},{"1":"5","2":"2","3":"21","4":"0","5":"2","6":"5.21","7":"2.21"},{"1":"1","2":"1","3":"22","4":"0","5":"1","6":"1.22","7":"1.22"},{"1":"1","2":"2","3":"22","4":"0","5":"1","6":"1.22","7":"2.22"},{"1":"2","2":"1","3":"22","4":"0","5":"2","6":"2.22","7":"1.22"},{"1":"2","2":"2","3":"22","4":"0","5":"2","6":"2.22","7":"2.22"},{"1":"3","2":"1","3":"22","4":"0","5":"2","6":"3.22","7":"1.22"},{"1":"3","2":"2","3":"22","4":"0","5":"1","6":"3.22","7":"2.22"},{"1":"4","2":"1","3":"22","4":"0","5":"1","6":"4.22","7":"1.22"},{"1":"4","2":"2","3":"22","4":"0","5":"1","6":"4.22","7":"2.22"},{"1":"5","2":"1","3":"22","4":"0","5":"2","6":"5.22","7":"1.22"},{"1":"5","2":"2","3":"22","4":"0","5":"2","6":"5.22","7":"2.22"},{"1":"1","2":"1","3":"23","4":"0","5":"3","6":"1.23","7":"1.23"},{"1":"1","2":"2","3":"23","4":"0","5":"1","6":"1.23","7":"2.23"},{"1":"2","2":"1","3":"23","4":"0","5":"2","6":"2.23","7":"1.23"},{"1":"2","2":"2","3":"23","4":"0","5":"2","6":"2.23","7":"2.23"},{"1":"3","2":"1","3":"23","4":"0","5":"3","6":"3.23","7":"1.23"},{"1":"3","2":"2","3":"23","4":"0","5":"2","6":"3.23","7":"2.23"},{"1":"4","2":"1","3":"23","4":"0","5":"1","6":"4.23","7":"1.23"},{"1":"4","2":"2","3":"23","4":"0","5":"1","6":"4.23","7":"2.23"},{"1":"5","2":"1","3":"23","4":"0","5":"2","6":"5.23","7":"1.23"},{"1":"5","2":"2","3":"23","4":"0","5":"1","6":"5.23","7":"2.23"},{"1":"1","2":"1","3":"24","4":"0","5":"1","6":"1.24","7":"1.24"},{"1":"1","2":"2","3":"24","4":"0","5":"1","6":"1.24","7":"2.24"},{"1":"2","2":"1","3":"24","4":"0","5":"2","6":"2.24","7":"1.24"},{"1":"2","2":"2","3":"24","4":"0","5":"2","6":"2.24","7":"2.24"},{"1":"3","2":"1","3":"24","4":"0","5":"2","6":"3.24","7":"1.24"},{"1":"3","2":"2","3":"24","4":"0","5":"1","6":"3.24","7":"2.24"},{"1":"4","2":"1","3":"24","4":"0","5":"1","6":"4.24","7":"1.24"},{"1":"4","2":"2","3":"24","4":"0","5":"1","6":"4.24","7":"2.24"},{"1":"5","2":"1","3":"24","4":"0","5":"1","6":"5.24","7":"1.24"},{"1":"5","2":"2","3":"24","4":"0","5":"2","6":"5.24","7":"2.24"},{"1":"1","2":"1","3":"25","4":"0","5":"3","6":"1.25","7":"1.25"},{"1":"1","2":"2","3":"25","4":"0","5":"4","6":"1.25","7":"2.25"},{"1":"2","2":"1","3":"25","4":"0","5":"4","6":"2.25","7":"1.25"},{"1":"2","2":"2","3":"25","4":"0","5":"3","6":"2.25","7":"2.25"},{"1":"3","2":"1","3":"25","4":"0","5":"4","6":"3.25","7":"1.25"},{"1":"3","2":"2","3":"25","4":"0","5":"4","6":"3.25","7":"2.25"},{"1":"4","2":"1","3":"25","4":"0","5":"2","6":"4.25","7":"1.25"},{"1":"4","2":"2","3":"25","4":"0","5":"3","6":"4.25","7":"2.25"},{"1":"5","2":"1","3":"25","4":"0","5":"1","6":"5.25","7":"1.25"},{"1":"5","2":"2","3":"25","4":"0","5":"3","6":"5.25","7":"2.25"},{"1":"1","2":"1","3":"26","4":"0","5":"1","6":"1.26","7":"1.26"},{"1":"1","2":"2","3":"26","4":"0","5":"2","6":"1.26","7":"2.26"},{"1":"2","2":"1","3":"26","4":"0","5":"2","6":"2.26","7":"1.26"},{"1":"2","2":"2","3":"26","4":"0","5":"2","6":"2.26","7":"2.26"},{"1":"3","2":"1","3":"26","4":"0","5":"1","6":"3.26","7":"1.26"},{"1":"3","2":"2","3":"26","4":"0","5":"1","6":"3.26","7":"2.26"},{"1":"4","2":"1","3":"26","4":"0","5":"1","6":"4.26","7":"1.26"},{"1":"4","2":"2","3":"26","4":"0","5":"2","6":"4.26","7":"2.26"},{"1":"5","2":"1","3":"26","4":"0","5":"1","6":"5.26","7":"1.26"},{"1":"5","2":"2","3":"26","4":"0","5":"2","6":"5.26","7":"2.26"},{"1":"1","2":"1","3":"27","4":"0","5":"1","6":"1.27","7":"1.27"},{"1":"1","2":"2","3":"27","4":"0","5":"1","6":"1.27","7":"2.27"},{"1":"2","2":"1","3":"27","4":"0","5":"2","6":"2.27","7":"1.27"},{"1":"2","2":"2","3":"27","4":"0","5":"2","6":"2.27","7":"2.27"},{"1":"3","2":"1","3":"27","4":"0","5":"1","6":"3.27","7":"1.27"},{"1":"3","2":"2","3":"27","4":"0","5":"1","6":"3.27","7":"2.27"},{"1":"4","2":"1","3":"27","4":"0","5":"1","6":"4.27","7":"1.27"},{"1":"4","2":"2","3":"27","4":"0","5":"1","6":"4.27","7":"2.27"},{"1":"5","2":"1","3":"27","4":"0","5":"1","6":"5.27","7":"1.27"},{"1":"5","2":"2","3":"27","4":"0","5":"2","6":"5.27","7":"2.27"},{"1":"1","2":"1","3":"28","4":"0","5":"2","6":"1.28","7":"1.28"},{"1":"1","2":"2","3":"28","4":"0","5":"3","6":"1.28","7":"2.28"},{"1":"2","2":"1","3":"28","4":"0","5":"2","6":"2.28","7":"1.28"},{"1":"2","2":"2","3":"28","4":"0","5":"2","6":"2.28","7":"2.28"},{"1":"3","2":"1","3":"28","4":"0","5":"3","6":"3.28","7":"1.28"},{"1":"3","2":"2","3":"28","4":"0","5":"5","6":"3.28","7":"2.28"},{"1":"4","2":"1","3":"28","4":"0","5":"1","6":"4.28","7":"1.28"},{"1":"4","2":"2","3":"28","4":"0","5":"2","6":"4.28","7":"2.28"},{"1":"5","2":"1","3":"28","4":"0","5":"2","6":"5.28","7":"1.28"},{"1":"5","2":"2","3":"28","4":"0","5":"3","6":"5.28","7":"2.28"},{"1":"1","2":"1","3":"29","4":"0","5":"1","6":"1.29","7":"1.29"},{"1":"1","2":"2","3":"29","4":"0","5":"1","6":"1.29","7":"2.29"},{"1":"2","2":"1","3":"29","4":"0","5":"2","6":"2.29","7":"1.29"},{"1":"2","2":"2","3":"29","4":"0","5":"2","6":"2.29","7":"2.29"},{"1":"3","2":"1","3":"29","4":"0","5":"2","6":"3.29","7":"1.29"},{"1":"3","2":"2","3":"29","4":"0","5":"1","6":"3.29","7":"2.29"},{"1":"4","2":"1","3":"29","4":"0","5":"1","6":"4.29","7":"1.29"},{"1":"4","2":"2","3":"29","4":"0","5":"1","6":"4.29","7":"2.29"},{"1":"5","2":"1","3":"29","4":"0","5":"1","6":"5.29","7":"1.29"},{"1":"5","2":"2","3":"29","4":"0","5":"2","6":"5.29","7":"2.29"},{"1":"1","2":"1","3":"30","4":"0","5":"4","6":"1.30","7":"1.30"},{"1":"1","2":"2","3":"30","4":"0","5":"2","6":"1.30","7":"2.30"},{"1":"2","2":"1","3":"30","4":"0","5":"3","6":"2.30","7":"1.30"},{"1":"2","2":"2","3":"30","4":"0","5":"2","6":"2.30","7":"2.30"},{"1":"3","2":"1","3":"30","4":"0","5":"2","6":"3.30","7":"1.30"},{"1":"3","2":"2","3":"30","4":"0","5":"2","6":"3.30","7":"2.30"},{"1":"4","2":"1","3":"30","4":"0","5":"2","6":"4.30","7":"1.30"},{"1":"4","2":"2","3":"30","4":"0","5":"2","6":"4.30","7":"2.30"},{"1":"5","2":"1","3":"30","4":"0","5":"1","6":"5.30","7":"1.30"},{"1":"5","2":"2","3":"30","4":"0","5":"1","6":"5.30","7":"2.30"},{"1":"1","2":"1","3":"31","4":"0","5":"1","6":"1.31","7":"1.31"},{"1":"1","2":"2","3":"31","4":"0","5":"2","6":"1.31","7":"2.31"},{"1":"2","2":"1","3":"31","4":"0","5":"2","6":"2.31","7":"1.31"},{"1":"2","2":"2","3":"31","4":"0","5":"2","6":"2.31","7":"2.31"},{"1":"3","2":"1","3":"31","4":"0","5":"1","6":"3.31","7":"1.31"},{"1":"3","2":"2","3":"31","4":"0","5":"1","6":"3.31","7":"2.31"},{"1":"4","2":"1","3":"31","4":"0","5":"1","6":"4.31","7":"1.31"},{"1":"4","2":"2","3":"31","4":"0","5":"1","6":"4.31","7":"2.31"},{"1":"5","2":"1","3":"31","4":"0","5":"2","6":"5.31","7":"1.31"},{"1":"5","2":"2","3":"31","4":"0","5":"2","6":"5.31","7":"2.31"},{"1":"1","2":"1","3":"32","4":"0","5":"1","6":"1.32","7":"1.32"},{"1":"1","2":"2","3":"32","4":"0","5":"1","6":"1.32","7":"2.32"},{"1":"2","2":"1","3":"32","4":"0","5":"2","6":"2.32","7":"1.32"},{"1":"2","2":"2","3":"32","4":"0","5":"1","6":"2.32","7":"2.32"},{"1":"3","2":"1","3":"32","4":"0","5":"1","6":"3.32","7":"1.32"},{"1":"3","2":"2","3":"32","4":"0","5":"1","6":"3.32","7":"2.32"},{"1":"4","2":"1","3":"32","4":"0","5":"1","6":"4.32","7":"1.32"},{"1":"4","2":"2","3":"32","4":"0","5":"1","6":"4.32","7":"2.32"},{"1":"5","2":"1","3":"32","4":"0","5":"1","6":"5.32","7":"1.32"},{"1":"5","2":"2","3":"32","4":"0","5":"1","6":"5.32","7":"2.32"},{"1":"1","2":"1","3":"33","4":"0","5":"1","6":"1.33","7":"1.33"},{"1":"1","2":"2","3":"33","4":"0","5":"4","6":"1.33","7":"2.33"},{"1":"2","2":"1","3":"33","4":"0","5":"2","6":"2.33","7":"1.33"},{"1":"2","2":"2","3":"33","4":"0","5":"2","6":"2.33","7":"2.33"},{"1":"3","2":"1","3":"33","4":"0","5":"2","6":"3.33","7":"1.33"},{"1":"3","2":"2","3":"33","4":"0","5":"2","6":"3.33","7":"2.33"},{"1":"4","2":"1","3":"33","4":"0","5":"1","6":"4.33","7":"1.33"},{"1":"4","2":"2","3":"33","4":"0","5":"1","6":"4.33","7":"2.33"},{"1":"5","2":"1","3":"33","4":"0","5":"1","6":"5.33","7":"1.33"},{"1":"5","2":"2","3":"33","4":"0","5":"2","6":"5.33","7":"2.33"},{"1":"1","2":"1","3":"34","4":"0","5":"1","6":"1.34","7":"1.34"},{"1":"1","2":"2","3":"34","4":"0","5":"3","6":"1.34","7":"2.34"},{"1":"2","2":"1","3":"34","4":"0","5":"2","6":"2.34","7":"1.34"},{"1":"2","2":"2","3":"34","4":"0","5":"2","6":"2.34","7":"2.34"},{"1":"3","2":"1","3":"34","4":"0","5":"2","6":"3.34","7":"1.34"},{"1":"3","2":"2","3":"34","4":"0","5":"1","6":"3.34","7":"2.34"},{"1":"4","2":"1","3":"34","4":"0","5":"1","6":"4.34","7":"1.34"},{"1":"4","2":"2","3":"34","4":"0","5":"1","6":"4.34","7":"2.34"},{"1":"5","2":"1","3":"34","4":"0","5":"2","6":"5.34","7":"1.34"},{"1":"5","2":"2","3":"34","4":"0","5":"2","6":"5.34","7":"2.34"},{"1":"1","2":"1","3":"35","4":"0","5":"1","6":"1.35","7":"1.35"},{"1":"1","2":"2","3":"35","4":"0","5":"2","6":"1.35","7":"2.35"},{"1":"2","2":"1","3":"35","4":"0","5":"2","6":"2.35","7":"1.35"},{"1":"2","2":"2","3":"35","4":"0","5":"1","6":"2.35","7":"2.35"},{"1":"3","2":"1","3":"35","4":"0","5":"2","6":"3.35","7":"1.35"},{"1":"3","2":"2","3":"35","4":"0","5":"2","6":"3.35","7":"2.35"},{"1":"4","2":"1","3":"35","4":"0","5":"1","6":"4.35","7":"1.35"},{"1":"4","2":"2","3":"35","4":"0","5":"2","6":"4.35","7":"2.35"},{"1":"5","2":"1","3":"35","4":"0","5":"3","6":"5.35","7":"1.35"},{"1":"5","2":"2","3":"35","4":"0","5":"2","6":"5.35","7":"2.35"},{"1":"1","2":"1","3":"36","4":"0","5":"3","6":"1.36","7":"1.36"},{"1":"1","2":"2","3":"36","4":"0","5":"3","6":"1.36","7":"2.36"},{"1":"2","2":"1","3":"36","4":"0","5":"2","6":"2.36","7":"1.36"},{"1":"2","2":"2","3":"36","4":"0","5":"2","6":"2.36","7":"2.36"},{"1":"3","2":"1","3":"36","4":"0","5":"4","6":"3.36","7":"1.36"},{"1":"3","2":"2","3":"36","4":"0","5":"2","6":"3.36","7":"2.36"},{"1":"4","2":"1","3":"36","4":"0","5":"1","6":"4.36","7":"1.36"},{"1":"4","2":"2","3":"36","4":"0","5":"2","6":"4.36","7":"2.36"},{"1":"5","2":"1","3":"36","4":"0","5":"1","6":"5.36","7":"1.36"},{"1":"5","2":"2","3":"36","4":"0","5":"2","6":"5.36","7":"2.36"},{"1":"1","2":"1","3":"37","4":"0","5":"1","6":"1.37","7":"1.37"},{"1":"1","2":"2","3":"37","4":"0","5":"1","6":"1.37","7":"2.37"},{"1":"2","2":"1","3":"37","4":"0","5":"2","6":"2.37","7":"1.37"},{"1":"2","2":"2","3":"37","4":"0","5":"2","6":"2.37","7":"2.37"},{"1":"3","2":"1","3":"37","4":"0","5":"1","6":"3.37","7":"1.37"},{"1":"3","2":"2","3":"37","4":"0","5":"2","6":"3.37","7":"2.37"},{"1":"4","2":"1","3":"37","4":"0","5":"1","6":"4.37","7":"1.37"},{"1":"4","2":"2","3":"37","4":"0","5":"1","6":"4.37","7":"2.37"},{"1":"5","2":"1","3":"37","4":"0","5":"2","6":"5.37","7":"1.37"},{"1":"5","2":"2","3":"37","4":"0","5":"1","6":"5.37","7":"2.37"},{"1":"1","2":"1","3":"38","4":"0","5":"2","6":"1.38","7":"1.38"},{"1":"1","2":"2","3":"38","4":"0","5":"2","6":"1.38","7":"2.38"},{"1":"2","2":"1","3":"38","4":"0","5":"2","6":"2.38","7":"1.38"},{"1":"2","2":"2","3":"38","4":"0","5":"2","6":"2.38","7":"2.38"},{"1":"3","2":"1","3":"38","4":"0","5":"2","6":"3.38","7":"1.38"},{"1":"3","2":"2","3":"38","4":"0","5":"1","6":"3.38","7":"2.38"},{"1":"4","2":"1","3":"38","4":"0","5":"1","6":"4.38","7":"1.38"},{"1":"4","2":"2","3":"38","4":"0","5":"1","6":"4.38","7":"2.38"},{"1":"5","2":"1","3":"38","4":"0","5":"2","6":"5.38","7":"1.38"},{"1":"5","2":"2","3":"38","4":"0","5":"1","6":"5.38","7":"2.38"},{"1":"1","2":"1","3":"39","4":"0","5":"1","6":"1.39","7":"1.39"},{"1":"1","2":"2","3":"39","4":"0","5":"3","6":"1.39","7":"2.39"},{"1":"2","2":"1","3":"39","4":"0","5":"2","6":"2.39","7":"1.39"},{"1":"2","2":"2","3":"39","4":"0","5":"2","6":"2.39","7":"2.39"},{"1":"3","2":"1","3":"39","4":"0","5":"1","6":"3.39","7":"1.39"},{"1":"3","2":"2","3":"39","4":"0","5":"2","6":"3.39","7":"2.39"},{"1":"4","2":"1","3":"39","4":"0","5":"1","6":"4.39","7":"1.39"},{"1":"4","2":"2","3":"39","4":"0","5":"2","6":"4.39","7":"2.39"},{"1":"5","2":"1","3":"39","4":"0","5":"1","6":"5.39","7":"1.39"},{"1":"5","2":"2","3":"39","4":"0","5":"2","6":"5.39","7":"2.39"},{"1":"1","2":"1","3":"40","4":"0","5":"2","6":"1.40","7":"1.40"},{"1":"1","2":"2","3":"40","4":"0","5":"1","6":"1.40","7":"2.40"},{"1":"2","2":"1","3":"40","4":"0","5":"2","6":"2.40","7":"1.40"},{"1":"2","2":"2","3":"40","4":"0","5":"2","6":"2.40","7":"2.40"},{"1":"3","2":"1","3":"40","4":"0","5":"4","6":"3.40","7":"1.40"},{"1":"3","2":"2","3":"40","4":"0","5":"2","6":"3.40","7":"2.40"},{"1":"4","2":"1","3":"40","4":"0","5":"1","6":"4.40","7":"1.40"},{"1":"4","2":"2","3":"40","4":"0","5":"1","6":"4.40","7":"2.40"},{"1":"5","2":"1","3":"40","4":"0","5":"1","6":"5.40","7":"1.40"},{"1":"5","2":"2","3":"40","4":"0","5":"1","6":"5.40","7":"2.40"},{"1":"1","2":"1","3":"41","4":"0","5":"1","6":"1.41","7":"1.41"},{"1":"1","2":"2","3":"41","4":"0","5":"2","6":"1.41","7":"2.41"},{"1":"2","2":"1","3":"41","4":"0","5":"2","6":"2.41","7":"1.41"},{"1":"2","2":"2","3":"41","4":"0","5":"3","6":"2.41","7":"2.41"},{"1":"3","2":"1","3":"41","4":"0","5":"1","6":"3.41","7":"1.41"},{"1":"3","2":"2","3":"41","4":"0","5":"2","6":"3.41","7":"2.41"},{"1":"4","2":"1","3":"41","4":"0","5":"1","6":"4.41","7":"1.41"},{"1":"4","2":"2","3":"41","4":"0","5":"1","6":"4.41","7":"2.41"},{"1":"5","2":"1","3":"41","4":"0","5":"1","6":"5.41","7":"1.41"},{"1":"5","2":"2","3":"41","4":"0","5":"2","6":"5.41","7":"2.41"},{"1":"1","2":"1","3":"42","4":"0","5":"1","6":"1.42","7":"1.42"},{"1":"1","2":"2","3":"42","4":"0","5":"2","6":"1.42","7":"2.42"},{"1":"2","2":"1","3":"42","4":"0","5":"2","6":"2.42","7":"1.42"},{"1":"2","2":"2","3":"42","4":"0","5":"1","6":"2.42","7":"2.42"},{"1":"3","2":"1","3":"42","4":"0","5":"2","6":"3.42","7":"1.42"},{"1":"3","2":"2","3":"42","4":"0","5":"1","6":"3.42","7":"2.42"},{"1":"4","2":"1","3":"42","4":"0","5":"1","6":"4.42","7":"1.42"},{"1":"4","2":"2","3":"42","4":"0","5":"1","6":"4.42","7":"2.42"},{"1":"5","2":"1","3":"42","4":"0","5":"3","6":"5.42","7":"1.42"},{"1":"5","2":"2","3":"42","4":"0","5":"1","6":"5.42","7":"2.42"},{"1":"1","2":"1","3":"43","4":"0","5":"2","6":"1.43","7":"1.43"},{"1":"1","2":"2","3":"43","4":"0","5":"2","6":"1.43","7":"2.43"},{"1":"2","2":"1","3":"43","4":"0","5":"2","6":"2.43","7":"1.43"},{"1":"2","2":"2","3":"43","4":"0","5":"2","6":"2.43","7":"2.43"},{"1":"3","2":"1","3":"43","4":"0","5":"1","6":"3.43","7":"1.43"},{"1":"3","2":"2","3":"43","4":"0","5":"1","6":"3.43","7":"2.43"},{"1":"4","2":"1","3":"43","4":"0","5":"1","6":"4.43","7":"1.43"},{"1":"4","2":"2","3":"43","4":"0","5":"1","6":"4.43","7":"2.43"},{"1":"5","2":"1","3":"43","4":"0","5":"3","6":"5.43","7":"1.43"},{"1":"5","2":"2","3":"43","4":"0","5":"1","6":"5.43","7":"2.43"},{"1":"1","2":"1","3":"44","4":"0","5":"3","6":"1.44","7":"1.44"},{"1":"1","2":"2","3":"44","4":"0","5":"3","6":"1.44","7":"2.44"},{"1":"2","2":"1","3":"44","4":"0","5":"2","6":"2.44","7":"1.44"},{"1":"2","2":"2","3":"44","4":"0","5":"2","6":"2.44","7":"2.44"},{"1":"3","2":"1","3":"44","4":"0","5":"1","6":"3.44","7":"1.44"},{"1":"3","2":"2","3":"44","4":"0","5":"3","6":"3.44","7":"2.44"},{"1":"4","2":"1","3":"44","4":"0","5":"1","6":"4.44","7":"1.44"},{"1":"4","2":"2","3":"44","4":"0","5":"1","6":"4.44","7":"2.44"},{"1":"5","2":"1","3":"44","4":"0","5":"3","6":"5.44","7":"1.44"},{"1":"5","2":"2","3":"44","4":"0","5":"3","6":"5.44","7":"2.44"},{"1":"1","2":"1","3":"45","4":"0","5":"3","6":"1.45","7":"1.45"},{"1":"1","2":"2","3":"45","4":"0","5":"3","6":"1.45","7":"2.45"},{"1":"2","2":"1","3":"45","4":"0","5":"2","6":"2.45","7":"1.45"},{"1":"2","2":"2","3":"45","4":"0","5":"3","6":"2.45","7":"2.45"},{"1":"3","2":"1","3":"45","4":"0","5":"2","6":"3.45","7":"1.45"},{"1":"3","2":"2","3":"45","4":"0","5":"2","6":"3.45","7":"2.45"},{"1":"4","2":"1","3":"45","4":"0","5":"1","6":"4.45","7":"1.45"},{"1":"4","2":"2","3":"45","4":"0","5":"2","6":"4.45","7":"2.45"},{"1":"5","2":"1","3":"45","4":"0","5":"2","6":"5.45","7":"1.45"},{"1":"5","2":"2","3":"45","4":"0","5":"2","6":"5.45","7":"2.45"},{"1":"1","2":"1","3":"46","4":"0","5":"1","6":"1.46","7":"1.46"},{"1":"1","2":"2","3":"46","4":"0","5":"1","6":"1.46","7":"2.46"},{"1":"2","2":"1","3":"46","4":"0","5":"2","6":"2.46","7":"1.46"},{"1":"2","2":"2","3":"46","4":"0","5":"2","6":"2.46","7":"2.46"},{"1":"3","2":"1","3":"46","4":"0","5":"2","6":"3.46","7":"1.46"},{"1":"3","2":"2","3":"46","4":"0","5":"1","6":"3.46","7":"2.46"},{"1":"4","2":"1","3":"46","4":"0","5":"1","6":"4.46","7":"1.46"},{"1":"4","2":"2","3":"46","4":"0","5":"1","6":"4.46","7":"2.46"},{"1":"5","2":"1","3":"46","4":"0","5":"1","6":"5.46","7":"1.46"},{"1":"5","2":"2","3":"46","4":"0","5":"1","6":"5.46","7":"2.46"},{"1":"1","2":"1","3":"47","4":"0","5":"3","6":"1.47","7":"1.47"},{"1":"1","2":"2","3":"47","4":"0","5":"1","6":"1.47","7":"2.47"},{"1":"2","2":"1","3":"47","4":"0","5":"2","6":"2.47","7":"1.47"},{"1":"2","2":"2","3":"47","4":"0","5":"2","6":"2.47","7":"2.47"},{"1":"3","2":"1","3":"47","4":"0","5":"2","6":"3.47","7":"1.47"},{"1":"3","2":"2","3":"47","4":"0","5":"1","6":"3.47","7":"2.47"},{"1":"4","2":"1","3":"47","4":"0","5":"1","6":"4.47","7":"1.47"},{"1":"4","2":"2","3":"47","4":"0","5":"2","6":"4.47","7":"2.47"},{"1":"5","2":"1","3":"47","4":"0","5":"1","6":"5.47","7":"1.47"},{"1":"5","2":"2","3":"47","4":"0","5":"2","6":"5.47","7":"2.47"},{"1":"1","2":"1","3":"48","4":"0","5":"1","6":"1.48","7":"1.48"},{"1":"1","2":"2","3":"48","4":"0","5":"1","6":"1.48","7":"2.48"},{"1":"2","2":"1","3":"48","4":"0","5":"2","6":"2.48","7":"1.48"},{"1":"2","2":"2","3":"48","4":"0","5":"2","6":"2.48","7":"2.48"},{"1":"3","2":"1","3":"48","4":"0","5":"2","6":"3.48","7":"1.48"},{"1":"3","2":"2","3":"48","4":"0","5":"1","6":"3.48","7":"2.48"},{"1":"4","2":"1","3":"48","4":"0","5":"1","6":"4.48","7":"1.48"},{"1":"4","2":"2","3":"48","4":"0","5":"1","6":"4.48","7":"2.48"},{"1":"5","2":"1","3":"48","4":"0","5":"1","6":"5.48","7":"1.48"},{"1":"5","2":"2","3":"48","4":"0","5":"2","6":"5.48","7":"2.48"},{"1":"1","2":"1","3":"49","4":"0","5":"1","6":"1.49","7":"1.49"},{"1":"1","2":"2","3":"49","4":"0","5":"3","6":"1.49","7":"2.49"},{"1":"2","2":"1","3":"49","4":"0","5":"2","6":"2.49","7":"1.49"},{"1":"2","2":"2","3":"49","4":"0","5":"2","6":"2.49","7":"2.49"},{"1":"3","2":"1","3":"49","4":"0","5":"2","6":"3.49","7":"1.49"},{"1":"3","2":"2","3":"49","4":"0","5":"2","6":"3.49","7":"2.49"},{"1":"4","2":"1","3":"49","4":"0","5":"3","6":"4.49","7":"1.49"},{"1":"4","2":"2","3":"49","4":"0","5":"2","6":"4.49","7":"2.49"},{"1":"5","2":"1","3":"49","4":"0","5":"2","6":"5.49","7":"1.49"},{"1":"5","2":"2","3":"49","4":"0","5":"3","6":"5.49","7":"2.49"},{"1":"1","2":"1","3":"50","4":"0","5":"3","6":"1.50","7":"1.50"},{"1":"1","2":"2","3":"50","4":"0","5":"3","6":"1.50","7":"2.50"},{"1":"2","2":"1","3":"50","4":"0","5":"2","6":"2.50","7":"1.50"},{"1":"2","2":"2","3":"50","4":"0","5":"2","6":"2.50","7":"2.50"},{"1":"3","2":"1","3":"50","4":"0","5":"2","6":"3.50","7":"1.50"},{"1":"3","2":"2","3":"50","4":"0","5":"3","6":"3.50","7":"2.50"},{"1":"4","2":"1","3":"50","4":"0","5":"3","6":"4.50","7":"1.50"},{"1":"4","2":"2","3":"50","4":"0","5":"1","6":"4.50","7":"2.50"},{"1":"5","2":"1","3":"50","4":"0","5":"1","6":"5.50","7":"1.50"},{"1":"5","2":"2","3":"50","4":"0","5":"3","6":"5.50","7":"2.50"},{"1":"1","2":"1","3":"51","4":"0","5":"3","6":"1.51","7":"1.51"},{"1":"1","2":"2","3":"51","4":"0","5":"3","6":"1.51","7":"2.51"},{"1":"2","2":"1","3":"51","4":"0","5":"2","6":"2.51","7":"1.51"},{"1":"2","2":"2","3":"51","4":"0","5":"2","6":"2.51","7":"2.51"},{"1":"3","2":"1","3":"51","4":"0","5":"3","6":"3.51","7":"1.51"},{"1":"3","2":"2","3":"51","4":"0","5":"3","6":"3.51","7":"2.51"},{"1":"4","2":"1","3":"51","4":"0","5":"1","6":"4.51","7":"1.51"},{"1":"4","2":"2","3":"51","4":"0","5":"2","6":"4.51","7":"2.51"},{"1":"5","2":"1","3":"51","4":"0","5":"1","6":"5.51","7":"1.51"},{"1":"5","2":"2","3":"51","4":"0","5":"2","6":"5.51","7":"2.51"},{"1":"1","2":"1","3":"52","4":"0","5":"1","6":"1.52","7":"1.52"},{"1":"1","2":"2","3":"52","4":"0","5":"1","6":"1.52","7":"2.52"},{"1":"2","2":"1","3":"52","4":"0","5":"2","6":"2.52","7":"1.52"},{"1":"2","2":"2","3":"52","4":"0","5":"2","6":"2.52","7":"2.52"},{"1":"3","2":"1","3":"52","4":"0","5":"2","6":"3.52","7":"1.52"},{"1":"3","2":"2","3":"52","4":"0","5":"1","6":"3.52","7":"2.52"},{"1":"4","2":"1","3":"52","4":"0","5":"1","6":"4.52","7":"1.52"},{"1":"4","2":"2","3":"52","4":"0","5":"2","6":"4.52","7":"2.52"},{"1":"5","2":"1","3":"52","4":"0","5":"1","6":"5.52","7":"1.52"},{"1":"5","2":"2","3":"52","4":"0","5":"1","6":"5.52","7":"2.52"},{"1":"1","2":"1","3":"53","4":"0","5":"1","6":"1.53","7":"1.53"},{"1":"1","2":"2","3":"53","4":"0","5":"1","6":"1.53","7":"2.53"},{"1":"2","2":"1","3":"53","4":"0","5":"2","6":"2.53","7":"1.53"},{"1":"2","2":"2","3":"53","4":"0","5":"2","6":"2.53","7":"2.53"},{"1":"3","2":"1","3":"53","4":"0","5":"1","6":"3.53","7":"1.53"},{"1":"3","2":"2","3":"53","4":"0","5":"1","6":"3.53","7":"2.53"},{"1":"4","2":"1","3":"53","4":"0","5":"1","6":"4.53","7":"1.53"},{"1":"4","2":"2","3":"53","4":"0","5":"1","6":"4.53","7":"2.53"},{"1":"5","2":"1","3":"53","4":"0","5":"1","6":"5.53","7":"1.53"},{"1":"5","2":"2","3":"53","4":"0","5":"2","6":"5.53","7":"2.53"},{"1":"1","2":"1","3":"54","4":"0","5":"1","6":"1.54","7":"1.54"},{"1":"1","2":"2","3":"54","4":"0","5":"3","6":"1.54","7":"2.54"},{"1":"2","2":"1","3":"54","4":"0","5":"2","6":"2.54","7":"1.54"},{"1":"2","2":"2","3":"54","4":"0","5":"2","6":"2.54","7":"2.54"},{"1":"3","2":"1","3":"54","4":"0","5":"1","6":"3.54","7":"1.54"},{"1":"3","2":"2","3":"54","4":"0","5":"3","6":"3.54","7":"2.54"},{"1":"4","2":"1","3":"54","4":"0","5":"1","6":"4.54","7":"1.54"},{"1":"4","2":"2","3":"54","4":"0","5":"1","6":"4.54","7":"2.54"},{"1":"5","2":"1","3":"54","4":"0","5":"1","6":"5.54","7":"1.54"},{"1":"5","2":"2","3":"54","4":"0","5":"2","6":"5.54","7":"2.54"},{"1":"1","2":"1","3":"55","4":"0","5":"1","6":"1.55","7":"1.55"},{"1":"1","2":"2","3":"55","4":"0","5":"4","6":"1.55","7":"2.55"},{"1":"2","2":"1","3":"55","4":"0","5":"2","6":"2.55","7":"1.55"},{"1":"2","2":"2","3":"55","4":"0","5":"3","6":"2.55","7":"2.55"},{"1":"3","2":"1","3":"55","4":"0","5":"2","6":"3.55","7":"1.55"},{"1":"3","2":"2","3":"55","4":"0","5":"2","6":"3.55","7":"2.55"},{"1":"4","2":"1","3":"55","4":"0","5":"1","6":"4.55","7":"1.55"},{"1":"4","2":"2","3":"55","4":"0","5":"1","6":"4.55","7":"2.55"},{"1":"5","2":"1","3":"55","4":"0","5":"1","6":"5.55","7":"1.55"},{"1":"5","2":"2","3":"55","4":"0","5":"2","6":"5.55","7":"2.55"},{"1":"1","2":"1","3":"56","4":"0","5":"1","6":"1.56","7":"1.56"},{"1":"1","2":"2","3":"56","4":"0","5":"1","6":"1.56","7":"2.56"},{"1":"2","2":"1","3":"56","4":"0","5":"2","6":"2.56","7":"1.56"},{"1":"2","2":"2","3":"56","4":"0","5":"2","6":"2.56","7":"2.56"},{"1":"3","2":"1","3":"56","4":"0","5":"1","6":"3.56","7":"1.56"},{"1":"3","2":"2","3":"56","4":"0","5":"2","6":"3.56","7":"2.56"},{"1":"4","2":"1","3":"56","4":"0","5":"1","6":"4.56","7":"1.56"},{"1":"4","2":"2","3":"56","4":"0","5":"1","6":"4.56","7":"2.56"},{"1":"5","2":"1","3":"56","4":"0","5":"1","6":"5.56","7":"1.56"},{"1":"5","2":"2","3":"56","4":"0","5":"2","6":"5.56","7":"2.56"},{"1":"1","2":"1","3":"57","4":"0","5":"1","6":"1.57","7":"1.57"},{"1":"1","2":"2","3":"57","4":"0","5":"2","6":"1.57","7":"2.57"},{"1":"2","2":"1","3":"57","4":"0","5":"2","6":"2.57","7":"1.57"},{"1":"2","2":"2","3":"57","4":"0","5":"2","6":"2.57","7":"2.57"},{"1":"3","2":"1","3":"57","4":"0","5":"1","6":"3.57","7":"1.57"},{"1":"3","2":"2","3":"57","4":"0","5":"1","6":"3.57","7":"2.57"},{"1":"4","2":"1","3":"57","4":"0","5":"1","6":"4.57","7":"1.57"},{"1":"4","2":"2","3":"57","4":"0","5":"1","6":"4.57","7":"2.57"},{"1":"5","2":"1","3":"57","4":"0","5":"1","6":"5.57","7":"1.57"},{"1":"5","2":"2","3":"57","4":"0","5":"1","6":"5.57","7":"2.57"},{"1":"1","2":"1","3":"58","4":"0","5":"2","6":"1.58","7":"1.58"},{"1":"1","2":"2","3":"58","4":"0","5":"4","6":"1.58","7":"2.58"},{"1":"2","2":"1","3":"58","4":"0","5":"4","6":"2.58","7":"1.58"},{"1":"2","2":"2","3":"58","4":"0","5":"3","6":"2.58","7":"2.58"},{"1":"3","2":"1","3":"58","4":"0","5":"2","6":"3.58","7":"1.58"},{"1":"3","2":"2","3":"58","4":"0","5":"2","6":"3.58","7":"2.58"},{"1":"4","2":"1","3":"58","4":"0","5":"1","6":"4.58","7":"1.58"},{"1":"4","2":"2","3":"58","4":"0","5":"2","6":"4.58","7":"2.58"},{"1":"5","2":"1","3":"58","4":"0","5":"3","6":"5.58","7":"1.58"},{"1":"5","2":"2","3":"58","4":"0","5":"2","6":"5.58","7":"2.58"},{"1":"1","2":"1","3":"59","4":"0","5":"2","6":"1.59","7":"1.59"},{"1":"1","2":"2","3":"59","4":"0","5":"2","6":"1.59","7":"2.59"},{"1":"2","2":"1","3":"59","4":"0","5":"3","6":"2.59","7":"1.59"},{"1":"2","2":"2","3":"59","4":"0","5":"2","6":"2.59","7":"2.59"},{"1":"3","2":"1","3":"59","4":"0","5":"2","6":"3.59","7":"1.59"},{"1":"3","2":"2","3":"59","4":"0","5":"3","6":"3.59","7":"2.59"},{"1":"4","2":"1","3":"59","4":"0","5":"1","6":"4.59","7":"1.59"},{"1":"4","2":"2","3":"59","4":"0","5":"1","6":"4.59","7":"2.59"},{"1":"5","2":"1","3":"59","4":"0","5":"4","6":"5.59","7":"1.59"},{"1":"5","2":"2","3":"59","4":"0","5":"2","6":"5.59","7":"2.59"},{"1":"1","2":"1","3":"60","4":"0","5":"1","6":"1.60","7":"1.60"},{"1":"1","2":"2","3":"60","4":"0","5":"1","6":"1.60","7":"2.60"},{"1":"2","2":"1","3":"60","4":"0","5":"2","6":"2.60","7":"1.60"},{"1":"2","2":"2","3":"60","4":"0","5":"2","6":"2.60","7":"2.60"},{"1":"3","2":"1","3":"60","4":"0","5":"1","6":"3.60","7":"1.60"},{"1":"3","2":"2","3":"60","4":"0","5":"2","6":"3.60","7":"2.60"},{"1":"4","2":"1","3":"60","4":"0","5":"1","6":"4.60","7":"1.60"},{"1":"4","2":"2","3":"60","4":"0","5":"2","6":"4.60","7":"2.60"},{"1":"5","2":"1","3":"60","4":"0","5":"1","6":"5.60","7":"1.60"},{"1":"5","2":"2","3":"60","4":"0","5":"2","6":"5.60","7":"2.60"},{"1":"1","2":"1","3":"61","4":"0","5":"1","6":"1.61","7":"1.61"},{"1":"1","2":"2","3":"61","4":"0","5":"2","6":"1.61","7":"2.61"},{"1":"2","2":"1","3":"61","4":"0","5":"2","6":"2.61","7":"1.61"},{"1":"2","2":"2","3":"61","4":"0","5":"2","6":"2.61","7":"2.61"},{"1":"3","2":"1","3":"61","4":"0","5":"1","6":"3.61","7":"1.61"},{"1":"3","2":"2","3":"61","4":"0","5":"3","6":"3.61","7":"2.61"},{"1":"4","2":"1","3":"61","4":"0","5":"1","6":"4.61","7":"1.61"},{"1":"4","2":"2","3":"61","4":"0","5":"1","6":"4.61","7":"2.61"},{"1":"5","2":"1","3":"61","4":"0","5":"2","6":"5.61","7":"1.61"},{"1":"5","2":"2","3":"61","4":"0","5":"2","6":"5.61","7":"2.61"},{"1":"1","2":"1","3":"62","4":"0","5":"1","6":"1.62","7":"1.62"},{"1":"1","2":"2","3":"62","4":"0","5":"4","6":"1.62","7":"2.62"},{"1":"2","2":"1","3":"62","4":"0","5":"3","6":"2.62","7":"1.62"},{"1":"2","2":"2","3":"62","4":"0","5":"2","6":"2.62","7":"2.62"},{"1":"3","2":"1","3":"62","4":"0","5":"5","6":"3.62","7":"1.62"},{"1":"3","2":"2","3":"62","4":"0","5":"4","6":"3.62","7":"2.62"},{"1":"4","2":"1","3":"62","4":"0","5":"1","6":"4.62","7":"1.62"},{"1":"4","2":"2","3":"62","4":"0","5":"1","6":"4.62","7":"2.62"},{"1":"5","2":"1","3":"62","4":"0","5":"3","6":"5.62","7":"1.62"},{"1":"5","2":"2","3":"62","4":"0","5":"3","6":"5.62","7":"2.62"},{"1":"1","2":"1","3":"63","4":"0","5":"1","6":"1.63","7":"1.63"},{"1":"1","2":"2","3":"63","4":"0","5":"1","6":"1.63","7":"2.63"},{"1":"2","2":"1","3":"63","4":"0","5":"2","6":"2.63","7":"1.63"},{"1":"2","2":"2","3":"63","4":"0","5":"2","6":"2.63","7":"2.63"},{"1":"3","2":"1","3":"63","4":"0","5":"1","6":"3.63","7":"1.63"},{"1":"3","2":"2","3":"63","4":"0","5":"1","6":"3.63","7":"2.63"},{"1":"4","2":"1","3":"63","4":"0","5":"1","6":"4.63","7":"1.63"},{"1":"4","2":"2","3":"63","4":"0","5":"1","6":"4.63","7":"2.63"},{"1":"5","2":"1","3":"63","4":"0","5":"1","6":"5.63","7":"1.63"},{"1":"5","2":"2","3":"63","4":"0","5":"1","6":"5.63","7":"2.63"},{"1":"1","2":"1","3":"64","4":"0","5":"3","6":"1.64","7":"1.64"},{"1":"1","2":"2","3":"64","4":"0","5":"4","6":"1.64","7":"2.64"},{"1":"2","2":"1","3":"64","4":"0","5":"2","6":"2.64","7":"1.64"},{"1":"2","2":"2","3":"64","4":"0","5":"2","6":"2.64","7":"2.64"},{"1":"3","2":"1","3":"64","4":"0","5":"4","6":"3.64","7":"1.64"},{"1":"3","2":"2","3":"64","4":"0","5":"2","6":"3.64","7":"2.64"},{"1":"4","2":"1","3":"64","4":"0","5":"3","6":"4.64","7":"1.64"},{"1":"4","2":"2","3":"64","4":"0","5":"3","6":"4.64","7":"2.64"},{"1":"5","2":"1","3":"64","4":"0","5":"2","6":"5.64","7":"1.64"},{"1":"5","2":"2","3":"64","4":"0","5":"2","6":"5.64","7":"2.64"},{"1":"1","2":"1","3":"65","4":"0","5":"3","6":"1.65","7":"1.65"},{"1":"1","2":"2","3":"65","4":"0","5":"4","6":"1.65","7":"2.65"},{"1":"2","2":"1","3":"65","4":"0","5":"2","6":"2.65","7":"1.65"},{"1":"2","2":"2","3":"65","4":"0","5":"2","6":"2.65","7":"2.65"},{"1":"3","2":"1","3":"65","4":"0","5":"2","6":"3.65","7":"1.65"},{"1":"3","2":"2","3":"65","4":"0","5":"4","6":"3.65","7":"2.65"},{"1":"4","2":"1","3":"65","4":"0","5":"1","6":"4.65","7":"1.65"},{"1":"4","2":"2","3":"65","4":"0","5":"2","6":"4.65","7":"2.65"},{"1":"5","2":"1","3":"65","4":"0","5":"1","6":"5.65","7":"1.65"},{"1":"5","2":"2","3":"65","4":"0","5":"3","6":"5.65","7":"2.65"},{"1":"1","2":"1","3":"66","4":"0","5":"2","6":"1.66","7":"1.66"},{"1":"1","2":"2","3":"66","4":"0","5":"2","6":"1.66","7":"2.66"},{"1":"2","2":"1","3":"66","4":"0","5":"2","6":"2.66","7":"1.66"},{"1":"2","2":"2","3":"66","4":"0","5":"2","6":"2.66","7":"2.66"},{"1":"3","2":"1","3":"66","4":"0","5":"1","6":"3.66","7":"1.66"},{"1":"3","2":"2","3":"66","4":"0","5":"2","6":"3.66","7":"2.66"},{"1":"4","2":"1","3":"66","4":"0","5":"1","6":"4.66","7":"1.66"},{"1":"4","2":"2","3":"66","4":"0","5":"3","6":"4.66","7":"2.66"},{"1":"5","2":"1","3":"66","4":"0","5":"2","6":"5.66","7":"1.66"},{"1":"5","2":"2","3":"66","4":"0","5":"3","6":"5.66","7":"2.66"},{"1":"1","2":"1","3":"67","4":"0","5":"1","6":"1.67","7":"1.67"},{"1":"1","2":"2","3":"67","4":"0","5":"1","6":"1.67","7":"2.67"},{"1":"2","2":"1","3":"67","4":"0","5":"2","6":"2.67","7":"1.67"},{"1":"2","2":"2","3":"67","4":"0","5":"1","6":"2.67","7":"2.67"},{"1":"3","2":"1","3":"67","4":"0","5":"2","6":"3.67","7":"1.67"},{"1":"3","2":"2","3":"67","4":"0","5":"1","6":"3.67","7":"2.67"},{"1":"4","2":"1","3":"67","4":"0","5":"1","6":"4.67","7":"1.67"},{"1":"4","2":"2","3":"67","4":"0","5":"2","6":"4.67","7":"2.67"},{"1":"5","2":"1","3":"67","4":"0","5":"1","6":"5.67","7":"1.67"},{"1":"5","2":"2","3":"67","4":"0","5":"1","6":"5.67","7":"2.67"},{"1":"1","2":"1","3":"68","4":"0","5":"1","6":"1.68","7":"1.68"},{"1":"1","2":"2","3":"68","4":"0","5":"1","6":"1.68","7":"2.68"},{"1":"2","2":"1","3":"68","4":"0","5":"2","6":"2.68","7":"1.68"},{"1":"2","2":"2","3":"68","4":"0","5":"2","6":"2.68","7":"2.68"},{"1":"3","2":"1","3":"68","4":"0","5":"1","6":"3.68","7":"1.68"},{"1":"3","2":"2","3":"68","4":"0","5":"2","6":"3.68","7":"2.68"},{"1":"4","2":"1","3":"68","4":"0","5":"1","6":"4.68","7":"1.68"},{"1":"4","2":"2","3":"68","4":"0","5":"1","6":"4.68","7":"2.68"},{"1":"5","2":"1","3":"68","4":"0","5":"1","6":"5.68","7":"1.68"},{"1":"5","2":"2","3":"68","4":"0","5":"1","6":"5.68","7":"2.68"},{"1":"1","2":"1","3":"69","4":"0","5":"1","6":"1.69","7":"1.69"},{"1":"1","2":"2","3":"69","4":"0","5":"1","6":"1.69","7":"2.69"},{"1":"2","2":"1","3":"69","4":"0","5":"2","6":"2.69","7":"1.69"},{"1":"2","2":"2","3":"69","4":"0","5":"2","6":"2.69","7":"2.69"},{"1":"3","2":"1","3":"69","4":"0","5":"2","6":"3.69","7":"1.69"},{"1":"3","2":"2","3":"69","4":"0","5":"1","6":"3.69","7":"2.69"},{"1":"4","2":"1","3":"69","4":"0","5":"1","6":"4.69","7":"1.69"},{"1":"4","2":"2","3":"69","4":"0","5":"1","6":"4.69","7":"2.69"},{"1":"5","2":"1","3":"69","4":"0","5":"3","6":"5.69","7":"1.69"},{"1":"5","2":"2","3":"69","4":"0","5":"1","6":"5.69","7":"2.69"},{"1":"1","2":"1","3":"70","4":"1","5":"5","6":"1.70","7":"1.70"},{"1":"1","2":"2","3":"70","4":"1","5":"5","6":"1.70","7":"2.70"},{"1":"2","2":"1","3":"70","4":"1","5":"5","6":"2.70","7":"1.70"},{"1":"2","2":"2","3":"70","4":"1","5":"5","6":"2.70","7":"2.70"},{"1":"3","2":"1","3":"70","4":"1","5":"5","6":"3.70","7":"1.70"},{"1":"3","2":"2","3":"70","4":"1","5":"5","6":"3.70","7":"2.70"},{"1":"4","2":"1","3":"70","4":"1","5":"5","6":"4.70","7":"1.70"},{"1":"4","2":"2","3":"70","4":"1","5":"5","6":"4.70","7":"2.70"},{"1":"5","2":"1","3":"70","4":"1","5":"5","6":"5.70","7":"1.70"},{"1":"5","2":"2","3":"70","4":"1","5":"5","6":"5.70","7":"2.70"},{"1":"1","2":"1","3":"71","4":"1","5":"5","6":"1.71","7":"1.71"},{"1":"1","2":"2","3":"71","4":"1","5":"3","6":"1.71","7":"2.71"},{"1":"2","2":"1","3":"71","4":"1","5":"3","6":"2.71","7":"1.71"},{"1":"2","2":"2","3":"71","4":"1","5":"3","6":"2.71","7":"2.71"},{"1":"3","2":"1","3":"71","4":"1","5":"4","6":"3.71","7":"1.71"},{"1":"3","2":"2","3":"71","4":"1","5":"2","6":"3.71","7":"2.71"},{"1":"4","2":"1","3":"71","4":"1","5":"5","6":"4.71","7":"1.71"},{"1":"4","2":"2","3":"71","4":"1","5":"4","6":"4.71","7":"2.71"},{"1":"5","2":"1","3":"71","4":"1","5":"2","6":"5.71","7":"1.71"},{"1":"5","2":"2","3":"71","4":"1","5":"2","6":"5.71","7":"2.71"},{"1":"1","2":"1","3":"72","4":"1","5":"5","6":"1.72","7":"1.72"},{"1":"1","2":"2","3":"72","4":"1","5":"5","6":"1.72","7":"2.72"},{"1":"2","2":"1","3":"72","4":"1","5":"5","6":"2.72","7":"1.72"},{"1":"2","2":"2","3":"72","4":"1","5":"5","6":"2.72","7":"2.72"},{"1":"3","2":"1","3":"72","4":"1","5":"5","6":"3.72","7":"1.72"},{"1":"3","2":"2","3":"72","4":"1","5":"5","6":"3.72","7":"2.72"},{"1":"4","2":"1","3":"72","4":"1","5":"5","6":"4.72","7":"1.72"},{"1":"4","2":"2","3":"72","4":"1","5":"5","6":"4.72","7":"2.72"},{"1":"5","2":"1","3":"72","4":"1","5":"5","6":"5.72","7":"1.72"},{"1":"5","2":"2","3":"72","4":"1","5":"5","6":"5.72","7":"2.72"},{"1":"1","2":"1","3":"73","4":"1","5":"5","6":"1.73","7":"1.73"},{"1":"1","2":"2","3":"73","4":"1","5":"5","6":"1.73","7":"2.73"},{"1":"2","2":"1","3":"73","4":"1","5":"5","6":"2.73","7":"1.73"},{"1":"2","2":"2","3":"73","4":"1","5":"5","6":"2.73","7":"2.73"},{"1":"3","2":"1","3":"73","4":"1","5":"5","6":"3.73","7":"1.73"},{"1":"3","2":"2","3":"73","4":"1","5":"5","6":"3.73","7":"2.73"},{"1":"4","2":"1","3":"73","4":"1","5":"5","6":"4.73","7":"1.73"},{"1":"4","2":"2","3":"73","4":"1","5":"5","6":"4.73","7":"2.73"},{"1":"5","2":"1","3":"73","4":"1","5":"2","6":"5.73","7":"1.73"},{"1":"5","2":"2","3":"73","4":"1","5":"4","6":"5.73","7":"2.73"},{"1":"1","2":"1","3":"74","4":"1","5":"4","6":"1.74","7":"1.74"},{"1":"1","2":"2","3":"74","4":"1","5":"5","6":"1.74","7":"2.74"},{"1":"2","2":"1","3":"74","4":"1","5":"5","6":"2.74","7":"1.74"},{"1":"2","2":"2","3":"74","4":"1","5":"5","6":"2.74","7":"2.74"},{"1":"3","2":"1","3":"74","4":"1","5":"5","6":"3.74","7":"1.74"},{"1":"3","2":"2","3":"74","4":"1","5":"5","6":"3.74","7":"2.74"},{"1":"4","2":"1","3":"74","4":"1","5":"5","6":"4.74","7":"1.74"},{"1":"4","2":"2","3":"74","4":"1","5":"5","6":"4.74","7":"2.74"},{"1":"5","2":"1","3":"74","4":"1","5":"5","6":"5.74","7":"1.74"},{"1":"5","2":"2","3":"74","4":"1","5":"5","6":"5.74","7":"2.74"},{"1":"1","2":"1","3":"75","4":"1","5":"5","6":"1.75","7":"1.75"},{"1":"1","2":"2","3":"75","4":"1","5":"5","6":"1.75","7":"2.75"},{"1":"2","2":"1","3":"75","4":"1","5":"5","6":"2.75","7":"1.75"},{"1":"2","2":"2","3":"75","4":"1","5":"5","6":"2.75","7":"2.75"},{"1":"3","2":"1","3":"75","4":"1","5":"5","6":"3.75","7":"1.75"},{"1":"3","2":"2","3":"75","4":"1","5":"5","6":"3.75","7":"2.75"},{"1":"4","2":"1","3":"75","4":"1","5":"5","6":"4.75","7":"1.75"},{"1":"4","2":"2","3":"75","4":"1","5":"5","6":"4.75","7":"2.75"},{"1":"5","2":"1","3":"75","4":"1","5":"5","6":"5.75","7":"1.75"},{"1":"5","2":"2","3":"75","4":"1","5":"5","6":"5.75","7":"2.75"},{"1":"1","2":"1","3":"76","4":"1","5":"5","6":"1.76","7":"1.76"},{"1":"1","2":"2","3":"76","4":"1","5":"5","6":"1.76","7":"2.76"},{"1":"2","2":"1","3":"76","4":"1","5":"5","6":"2.76","7":"1.76"},{"1":"2","2":"2","3":"76","4":"1","5":"5","6":"2.76","7":"2.76"},{"1":"3","2":"1","3":"76","4":"1","5":"5","6":"3.76","7":"1.76"},{"1":"3","2":"2","3":"76","4":"1","5":"5","6":"3.76","7":"2.76"},{"1":"4","2":"1","3":"76","4":"1","5":"5","6":"4.76","7":"1.76"},{"1":"4","2":"2","3":"76","4":"1","5":"5","6":"4.76","7":"2.76"},{"1":"5","2":"1","3":"76","4":"1","5":"5","6":"5.76","7":"1.76"},{"1":"5","2":"2","3":"76","4":"1","5":"5","6":"5.76","7":"2.76"},{"1":"1","2":"1","3":"77","4":"1","5":"5","6":"1.77","7":"1.77"},{"1":"1","2":"2","3":"77","4":"1","5":"5","6":"1.77","7":"2.77"},{"1":"2","2":"1","3":"77","4":"1","5":"4","6":"2.77","7":"1.77"},{"1":"2","2":"2","3":"77","4":"1","5":"5","6":"2.77","7":"2.77"},{"1":"3","2":"1","3":"77","4":"1","5":"5","6":"3.77","7":"1.77"},{"1":"3","2":"2","3":"77","4":"1","5":"5","6":"3.77","7":"2.77"},{"1":"4","2":"1","3":"77","4":"1","5":"5","6":"4.77","7":"1.77"},{"1":"4","2":"2","3":"77","4":"1","5":"5","6":"4.77","7":"2.77"},{"1":"5","2":"1","3":"77","4":"1","5":"5","6":"5.77","7":"1.77"},{"1":"5","2":"2","3":"77","4":"1","5":"5","6":"5.77","7":"2.77"},{"1":"1","2":"1","3":"78","4":"1","5":"4","6":"1.78","7":"1.78"},{"1":"1","2":"2","3":"78","4":"1","5":"4","6":"1.78","7":"2.78"},{"1":"2","2":"1","3":"78","4":"1","5":"2","6":"2.78","7":"1.78"},{"1":"2","2":"2","3":"78","4":"1","5":"2","6":"2.78","7":"2.78"},{"1":"3","2":"1","3":"78","4":"1","5":"5","6":"3.78","7":"1.78"},{"1":"3","2":"2","3":"78","4":"1","5":"5","6":"3.78","7":"2.78"},{"1":"4","2":"1","3":"78","4":"1","5":"5","6":"4.78","7":"1.78"},{"1":"4","2":"2","3":"78","4":"1","5":"4","6":"4.78","7":"2.78"},{"1":"5","2":"1","3":"78","4":"1","5":"1","6":"5.78","7":"1.78"},{"1":"5","2":"2","3":"78","4":"1","5":"5","6":"5.78","7":"2.78"},{"1":"1","2":"1","3":"79","4":"1","5":"5","6":"1.79","7":"1.79"},{"1":"1","2":"2","3":"79","4":"1","5":"5","6":"1.79","7":"2.79"},{"1":"2","2":"1","3":"79","4":"1","5":"5","6":"2.79","7":"1.79"},{"1":"2","2":"2","3":"79","4":"1","5":"5","6":"2.79","7":"2.79"},{"1":"3","2":"1","3":"79","4":"1","5":"5","6":"3.79","7":"1.79"},{"1":"3","2":"2","3":"79","4":"1","5":"5","6":"3.79","7":"2.79"},{"1":"4","2":"1","3":"79","4":"1","5":"5","6":"4.79","7":"1.79"},{"1":"4","2":"2","3":"79","4":"1","5":"5","6":"4.79","7":"2.79"},{"1":"5","2":"1","3":"79","4":"1","5":"5","6":"5.79","7":"1.79"},{"1":"5","2":"2","3":"79","4":"1","5":"4","6":"5.79","7":"2.79"},{"1":"1","2":"1","3":"80","4":"1","5":"5","6":"1.80","7":"1.80"},{"1":"1","2":"2","3":"80","4":"1","5":"5","6":"1.80","7":"2.80"},{"1":"2","2":"1","3":"80","4":"1","5":"5","6":"2.80","7":"1.80"},{"1":"2","2":"2","3":"80","4":"1","5":"5","6":"2.80","7":"2.80"},{"1":"3","2":"1","3":"80","4":"1","5":"5","6":"3.80","7":"1.80"},{"1":"3","2":"2","3":"80","4":"1","5":"5","6":"3.80","7":"2.80"},{"1":"4","2":"1","3":"80","4":"1","5":"5","6":"4.80","7":"1.80"},{"1":"4","2":"2","3":"80","4":"1","5":"5","6":"4.80","7":"2.80"},{"1":"5","2":"1","3":"80","4":"1","5":"4","6":"5.80","7":"1.80"},{"1":"5","2":"2","3":"80","4":"1","5":"5","6":"5.80","7":"2.80"},{"1":"1","2":"1","3":"81","4":"1","5":"5","6":"1.81","7":"1.81"},{"1":"1","2":"2","3":"81","4":"1","5":"5","6":"1.81","7":"2.81"},{"1":"2","2":"1","3":"81","4":"1","5":"5","6":"2.81","7":"1.81"},{"1":"2","2":"2","3":"81","4":"1","5":"5","6":"2.81","7":"2.81"},{"1":"3","2":"1","3":"81","4":"1","5":"5","6":"3.81","7":"1.81"},{"1":"3","2":"2","3":"81","4":"1","5":"5","6":"3.81","7":"2.81"},{"1":"4","2":"1","3":"81","4":"1","5":"5","6":"4.81","7":"1.81"},{"1":"4","2":"2","3":"81","4":"1","5":"5","6":"4.81","7":"2.81"},{"1":"5","2":"1","3":"81","4":"1","5":"5","6":"5.81","7":"1.81"},{"1":"5","2":"2","3":"81","4":"1","5":"5","6":"5.81","7":"2.81"},{"1":"1","2":"1","3":"82","4":"1","5":"4","6":"1.82","7":"1.82"},{"1":"1","2":"2","3":"82","4":"1","5":"5","6":"1.82","7":"2.82"},{"1":"2","2":"1","3":"82","4":"1","5":"4","6":"2.82","7":"1.82"},{"1":"2","2":"2","3":"82","4":"1","5":"3","6":"2.82","7":"2.82"},{"1":"3","2":"1","3":"82","4":"1","5":"5","6":"3.82","7":"1.82"},{"1":"3","2":"2","3":"82","4":"1","5":"3","6":"3.82","7":"2.82"},{"1":"4","2":"1","3":"82","4":"1","5":"5","6":"4.82","7":"1.82"},{"1":"4","2":"2","3":"82","4":"1","5":"4","6":"4.82","7":"2.82"},{"1":"5","2":"1","3":"82","4":"1","5":"4","6":"5.82","7":"1.82"},{"1":"5","2":"2","3":"82","4":"1","5":"3","6":"5.82","7":"2.82"},{"1":"1","2":"1","3":"83","4":"1","5":"3","6":"1.83","7":"1.83"},{"1":"1","2":"2","3":"83","4":"1","5":"4","6":"1.83","7":"2.83"},{"1":"2","2":"1","3":"83","4":"1","5":"4","6":"2.83","7":"1.83"},{"1":"2","2":"2","3":"83","4":"1","5":"4","6":"2.83","7":"2.83"},{"1":"3","2":"1","3":"83","4":"1","5":"4","6":"3.83","7":"1.83"},{"1":"3","2":"2","3":"83","4":"1","5":"5","6":"3.83","7":"2.83"},{"1":"4","2":"1","3":"83","4":"1","5":"5","6":"4.83","7":"1.83"},{"1":"4","2":"2","3":"83","4":"1","5":"5","6":"4.83","7":"2.83"},{"1":"5","2":"1","3":"83","4":"1","5":"5","6":"5.83","7":"1.83"},{"1":"5","2":"2","3":"83","4":"1","5":"4","6":"5.83","7":"2.83"},{"1":"1","2":"1","3":"84","4":"1","5":"4","6":"1.84","7":"1.84"},{"1":"1","2":"2","3":"84","4":"1","5":"4","6":"1.84","7":"2.84"},{"1":"2","2":"1","3":"84","4":"1","5":"2","6":"2.84","7":"1.84"},{"1":"2","2":"2","3":"84","4":"1","5":"4","6":"2.84","7":"2.84"},{"1":"3","2":"1","3":"84","4":"1","5":"2","6":"3.84","7":"1.84"},{"1":"3","2":"2","3":"84","4":"1","5":"4","6":"3.84","7":"2.84"},{"1":"4","2":"1","3":"84","4":"1","5":"5","6":"4.84","7":"1.84"},{"1":"4","2":"2","3":"84","4":"1","5":"5","6":"4.84","7":"2.84"},{"1":"5","2":"1","3":"84","4":"1","5":"2","6":"5.84","7":"1.84"},{"1":"5","2":"2","3":"84","4":"1","5":"3","6":"5.84","7":"2.84"},{"1":"1","2":"1","3":"85","4":"1","5":"2","6":"1.85","7":"1.85"},{"1":"1","2":"2","3":"85","4":"1","5":"3","6":"1.85","7":"2.85"},{"1":"2","2":"1","3":"85","4":"1","5":"2","6":"2.85","7":"1.85"},{"1":"2","2":"2","3":"85","4":"1","5":"2","6":"2.85","7":"2.85"},{"1":"3","2":"1","3":"85","4":"1","5":"3","6":"3.85","7":"1.85"},{"1":"3","2":"2","3":"85","4":"1","5":"1","6":"3.85","7":"2.85"},{"1":"4","2":"1","3":"85","4":"1","5":"1","6":"4.85","7":"1.85"},{"1":"4","2":"2","3":"85","4":"1","5":"5","6":"4.85","7":"2.85"},{"1":"5","2":"1","3":"85","4":"1","5":"2","6":"5.85","7":"1.85"},{"1":"5","2":"2","3":"85","4":"1","5":"3","6":"5.85","7":"2.85"},{"1":"1","2":"1","3":"86","4":"1","5":"4","6":"1.86","7":"1.86"},{"1":"1","2":"2","3":"86","4":"1","5":"3","6":"1.86","7":"2.86"},{"1":"2","2":"1","3":"86","4":"1","5":"2","6":"2.86","7":"1.86"},{"1":"2","2":"2","3":"86","4":"1","5":"4","6":"2.86","7":"2.86"},{"1":"3","2":"1","3":"86","4":"1","5":"5","6":"3.86","7":"1.86"},{"1":"3","2":"2","3":"86","4":"1","5":"4","6":"3.86","7":"2.86"},{"1":"4","2":"1","3":"86","4":"1","5":"5","6":"4.86","7":"1.86"},{"1":"4","2":"2","3":"86","4":"1","5":"5","6":"4.86","7":"2.86"},{"1":"5","2":"1","3":"86","4":"1","5":"3","6":"5.86","7":"1.86"},{"1":"5","2":"2","3":"86","4":"1","5":"3","6":"5.86","7":"2.86"},{"1":"1","2":"1","3":"87","4":"1","5":"5","6":"1.87","7":"1.87"},{"1":"1","2":"2","3":"87","4":"1","5":"5","6":"1.87","7":"2.87"},{"1":"2","2":"1","3":"87","4":"1","5":"5","6":"2.87","7":"1.87"},{"1":"2","2":"2","3":"87","4":"1","5":"5","6":"2.87","7":"2.87"},{"1":"3","2":"1","3":"87","4":"1","5":"5","6":"3.87","7":"1.87"},{"1":"3","2":"2","3":"87","4":"1","5":"5","6":"3.87","7":"2.87"},{"1":"4","2":"1","3":"87","4":"1","5":"5","6":"4.87","7":"1.87"},{"1":"4","2":"2","3":"87","4":"1","5":"5","6":"4.87","7":"2.87"},{"1":"5","2":"1","3":"87","4":"1","5":"5","6":"5.87","7":"1.87"},{"1":"5","2":"2","3":"87","4":"1","5":"5","6":"5.87","7":"2.87"},{"1":"1","2":"1","3":"88","4":"1","5":"5","6":"1.88","7":"1.88"},{"1":"1","2":"2","3":"88","4":"1","5":"5","6":"1.88","7":"2.88"},{"1":"2","2":"1","3":"88","4":"1","5":"5","6":"2.88","7":"1.88"},{"1":"2","2":"2","3":"88","4":"1","5":"4","6":"2.88","7":"2.88"},{"1":"3","2":"1","3":"88","4":"1","5":"5","6":"3.88","7":"1.88"},{"1":"3","2":"2","3":"88","4":"1","5":"5","6":"3.88","7":"2.88"},{"1":"4","2":"1","3":"88","4":"1","5":"5","6":"4.88","7":"1.88"},{"1":"4","2":"2","3":"88","4":"1","5":"5","6":"4.88","7":"2.88"},{"1":"5","2":"1","3":"88","4":"1","5":"5","6":"5.88","7":"1.88"},{"1":"5","2":"2","3":"88","4":"1","5":"5","6":"5.88","7":"2.88"},{"1":"1","2":"1","3":"89","4":"1","5":"5","6":"1.89","7":"1.89"},{"1":"1","2":"2","3":"89","4":"1","5":"5","6":"1.89","7":"2.89"},{"1":"2","2":"1","3":"89","4":"1","5":"5","6":"2.89","7":"1.89"},{"1":"2","2":"2","3":"89","4":"1","5":"5","6":"2.89","7":"2.89"},{"1":"3","2":"1","3":"89","4":"1","5":"5","6":"3.89","7":"1.89"},{"1":"3","2":"2","3":"89","4":"1","5":"5","6":"3.89","7":"2.89"},{"1":"4","2":"1","3":"89","4":"1","5":"5","6":"4.89","7":"1.89"},{"1":"4","2":"2","3":"89","4":"1","5":"5","6":"4.89","7":"2.89"},{"1":"5","2":"1","3":"89","4":"1","5":"5","6":"5.89","7":"1.89"},{"1":"5","2":"2","3":"89","4":"1","5":"5","6":"5.89","7":"2.89"},{"1":"1","2":"1","3":"90","4":"1","5":"5","6":"1.90","7":"1.90"},{"1":"1","2":"2","3":"90","4":"1","5":"5","6":"1.90","7":"2.90"},{"1":"2","2":"1","3":"90","4":"1","5":"5","6":"2.90","7":"1.90"},{"1":"2","2":"2","3":"90","4":"1","5":"5","6":"2.90","7":"2.90"},{"1":"3","2":"1","3":"90","4":"1","5":"5","6":"3.90","7":"1.90"},{"1":"3","2":"2","3":"90","4":"1","5":"5","6":"3.90","7":"2.90"},{"1":"4","2":"1","3":"90","4":"1","5":"5","6":"4.90","7":"1.90"},{"1":"4","2":"2","3":"90","4":"1","5":"5","6":"4.90","7":"2.90"},{"1":"5","2":"1","3":"90","4":"1","5":"5","6":"5.90","7":"1.90"},{"1":"5","2":"2","3":"90","4":"1","5":"5","6":"5.90","7":"2.90"},{"1":"1","2":"1","3":"91","4":"1","5":"5","6":"1.91","7":"1.91"},{"1":"1","2":"2","3":"91","4":"1","5":"5","6":"1.91","7":"2.91"},{"1":"2","2":"1","3":"91","4":"1","5":"5","6":"2.91","7":"1.91"},{"1":"2","2":"2","3":"91","4":"1","5":"5","6":"2.91","7":"2.91"},{"1":"3","2":"1","3":"91","4":"1","5":"5","6":"3.91","7":"1.91"},{"1":"3","2":"2","3":"91","4":"1","5":"5","6":"3.91","7":"2.91"},{"1":"4","2":"1","3":"91","4":"1","5":"5","6":"4.91","7":"1.91"},{"1":"4","2":"2","3":"91","4":"1","5":"5","6":"4.91","7":"2.91"},{"1":"5","2":"1","3":"91","4":"1","5":"5","6":"5.91","7":"1.91"},{"1":"5","2":"2","3":"91","4":"1","5":"5","6":"5.91","7":"2.91"},{"1":"1","2":"1","3":"92","4":"1","5":"5","6":"1.92","7":"1.92"},{"1":"1","2":"2","3":"92","4":"1","5":"5","6":"1.92","7":"2.92"},{"1":"2","2":"1","3":"92","4":"1","5":"5","6":"2.92","7":"1.92"},{"1":"2","2":"2","3":"92","4":"1","5":"4","6":"2.92","7":"2.92"},{"1":"3","2":"1","3":"92","4":"1","5":"5","6":"3.92","7":"1.92"},{"1":"3","2":"2","3":"92","4":"1","5":"5","6":"3.92","7":"2.92"},{"1":"4","2":"1","3":"92","4":"1","5":"5","6":"4.92","7":"1.92"},{"1":"4","2":"2","3":"92","4":"1","5":"5","6":"4.92","7":"2.92"},{"1":"5","2":"1","3":"92","4":"1","5":"5","6":"5.92","7":"1.92"},{"1":"5","2":"2","3":"92","4":"1","5":"5","6":"5.92","7":"2.92"},{"1":"1","2":"1","3":"93","4":"1","5":"5","6":"1.93","7":"1.93"},{"1":"1","2":"2","3":"93","4":"1","5":"5","6":"1.93","7":"2.93"},{"1":"2","2":"1","3":"93","4":"1","5":"5","6":"2.93","7":"1.93"},{"1":"2","2":"2","3":"93","4":"1","5":"5","6":"2.93","7":"2.93"},{"1":"3","2":"1","3":"93","4":"1","5":"5","6":"3.93","7":"1.93"},{"1":"3","2":"2","3":"93","4":"1","5":"5","6":"3.93","7":"2.93"},{"1":"4","2":"1","3":"93","4":"1","5":"5","6":"4.93","7":"1.93"},{"1":"4","2":"2","3":"93","4":"1","5":"5","6":"4.93","7":"2.93"},{"1":"5","2":"1","3":"93","4":"1","5":"4","6":"5.93","7":"1.93"},{"1":"5","2":"2","3":"93","4":"1","5":"5","6":"5.93","7":"2.93"},{"1":"1","2":"1","3":"94","4":"1","5":"1","6":"1.94","7":"1.94"},{"1":"1","2":"2","3":"94","4":"1","5":"3","6":"1.94","7":"2.94"},{"1":"2","2":"1","3":"94","4":"1","5":"2","6":"2.94","7":"1.94"},{"1":"2","2":"2","3":"94","4":"1","5":"2","6":"2.94","7":"2.94"},{"1":"3","2":"1","3":"94","4":"1","5":"2","6":"3.94","7":"1.94"},{"1":"3","2":"2","3":"94","4":"1","5":"2","6":"3.94","7":"2.94"},{"1":"4","2":"1","3":"94","4":"1","5":"5","6":"4.94","7":"1.94"},{"1":"4","2":"2","3":"94","4":"1","5":"4","6":"4.94","7":"2.94"},{"1":"5","2":"1","3":"94","4":"1","5":"1","6":"5.94","7":"1.94"},{"1":"5","2":"2","3":"94","4":"1","5":"2","6":"5.94","7":"2.94"},{"1":"1","2":"1","3":"95","4":"1","5":"5","6":"1.95","7":"1.95"},{"1":"1","2":"2","3":"95","4":"1","5":"5","6":"1.95","7":"2.95"},{"1":"2","2":"1","3":"95","4":"1","5":"4","6":"2.95","7":"1.95"},{"1":"2","2":"2","3":"95","4":"1","5":"5","6":"2.95","7":"2.95"},{"1":"3","2":"1","3":"95","4":"1","5":"5","6":"3.95","7":"1.95"},{"1":"3","2":"2","3":"95","4":"1","5":"5","6":"3.95","7":"2.95"},{"1":"4","2":"1","3":"95","4":"1","5":"5","6":"4.95","7":"1.95"},{"1":"4","2":"2","3":"95","4":"1","5":"5","6":"4.95","7":"2.95"},{"1":"5","2":"1","3":"95","4":"1","5":"4","6":"5.95","7":"1.95"},{"1":"5","2":"2","3":"95","4":"1","5":"5","6":"5.95","7":"2.95"},{"1":"1","2":"1","3":"96","4":"1","5":"4","6":"1.96","7":"1.96"},{"1":"1","2":"2","3":"96","4":"1","5":"5","6":"1.96","7":"2.96"},{"1":"2","2":"1","3":"96","4":"1","5":"3","6":"2.96","7":"1.96"},{"1":"2","2":"2","3":"96","4":"1","5":"2","6":"2.96","7":"2.96"},{"1":"3","2":"1","3":"96","4":"1","5":"2","6":"3.96","7":"1.96"},{"1":"3","2":"2","3":"96","4":"1","5":"3","6":"3.96","7":"2.96"},{"1":"4","2":"1","3":"96","4":"1","5":"4","6":"4.96","7":"1.96"},{"1":"4","2":"2","3":"96","4":"1","5":"5","6":"4.96","7":"2.96"},{"1":"5","2":"1","3":"96","4":"1","5":"4","6":"5.96","7":"1.96"},{"1":"5","2":"2","3":"96","4":"1","5":"1","6":"5.96","7":"2.96"},{"1":"1","2":"1","3":"97","4":"1","5":"4","6":"1.97","7":"1.97"},{"1":"1","2":"2","3":"97","4":"1","5":"3","6":"1.97","7":"2.97"},{"1":"2","2":"1","3":"97","4":"1","5":"3","6":"2.97","7":"1.97"},{"1":"2","2":"2","3":"97","4":"1","5":"3","6":"2.97","7":"2.97"},{"1":"3","2":"1","3":"97","4":"1","5":"2","6":"3.97","7":"1.97"},{"1":"3","2":"2","3":"97","4":"1","5":"3","6":"3.97","7":"2.97"},{"1":"4","2":"1","3":"97","4":"1","5":"5","6":"4.97","7":"1.97"},{"1":"4","2":"2","3":"97","4":"1","5":"4","6":"4.97","7":"2.97"},{"1":"5","2":"1","3":"97","4":"1","5":"3","6":"5.97","7":"1.97"},{"1":"5","2":"2","3":"97","4":"1","5":"3","6":"5.97","7":"2.97"},{"1":"1","2":"1","3":"98","4":"1","5":"5","6":"1.98","7":"1.98"},{"1":"1","2":"2","3":"98","4":"1","5":"5","6":"1.98","7":"2.98"},{"1":"2","2":"1","3":"98","4":"1","5":"5","6":"2.98","7":"1.98"},{"1":"2","2":"2","3":"98","4":"1","5":"5","6":"2.98","7":"2.98"},{"1":"3","2":"1","3":"98","4":"1","5":"5","6":"3.98","7":"1.98"},{"1":"3","2":"2","3":"98","4":"1","5":"5","6":"3.98","7":"2.98"},{"1":"4","2":"1","3":"98","4":"1","5":"4","6":"4.98","7":"1.98"},{"1":"4","2":"2","3":"98","4":"1","5":"4","6":"4.98","7":"2.98"},{"1":"5","2":"1","3":"98","4":"1","5":"2","6":"5.98","7":"1.98"},{"1":"5","2":"2","3":"98","4":"1","5":"3","6":"5.98","7":"2.98"},{"1":"1","2":"1","3":"99","4":"1","5":"4","6":"1.99","7":"1.99"},{"1":"1","2":"2","3":"99","4":"1","5":"5","6":"1.99","7":"2.99"},{"1":"2","2":"1","3":"99","4":"1","5":"4","6":"2.99","7":"1.99"},{"1":"2","2":"2","3":"99","4":"1","5":"5","6":"2.99","7":"2.99"},{"1":"3","2":"1","3":"99","4":"1","5":"5","6":"3.99","7":"1.99"},{"1":"3","2":"2","3":"99","4":"1","5":"5","6":"3.99","7":"2.99"},{"1":"4","2":"1","3":"99","4":"1","5":"4","6":"4.99","7":"1.99"},{"1":"4","2":"2","3":"99","4":"1","5":"5","6":"4.99","7":"2.99"},{"1":"5","2":"1","3":"99","4":"1","5":"2","6":"5.99","7":"1.99"},{"1":"5","2":"2","3":"99","4":"1","5":"2","6":"5.99","7":"2.99"},{"1":"1","2":"1","3":"100","4":"1","5":"5","6":"1.100","7":"1.100"},{"1":"1","2":"2","3":"100","4":"1","5":"5","6":"1.100","7":"2.100"},{"1":"2","2":"1","3":"100","4":"1","5":"5","6":"2.100","7":"1.100"},{"1":"2","2":"2","3":"100","4":"1","5":"5","6":"2.100","7":"2.100"},{"1":"3","2":"1","3":"100","4":"1","5":"5","6":"3.100","7":"1.100"},{"1":"3","2":"2","3":"100","4":"1","5":"5","6":"3.100","7":"2.100"},{"1":"4","2":"1","3":"100","4":"1","5":"5","6":"4.100","7":"1.100"},{"1":"4","2":"2","3":"100","4":"1","5":"5","6":"4.100","7":"2.100"},{"1":"5","2":"1","3":"100","4":"1","5":"1","6":"5.100","7":"1.100"},{"1":"5","2":"2","3":"100","4":"1","5":"5","6":"5.100","7":"2.100"},{"1":"1","2":"1","3":"101","4":"1","5":"5","6":"1.101","7":"1.101"},{"1":"1","2":"2","3":"101","4":"1","5":"5","6":"1.101","7":"2.101"},{"1":"2","2":"1","3":"101","4":"1","5":"5","6":"2.101","7":"1.101"},{"1":"2","2":"2","3":"101","4":"1","5":"3","6":"2.101","7":"2.101"},{"1":"3","2":"1","3":"101","4":"1","5":"5","6":"3.101","7":"1.101"},{"1":"3","2":"2","3":"101","4":"1","5":"4","6":"3.101","7":"2.101"},{"1":"4","2":"1","3":"101","4":"1","5":"5","6":"4.101","7":"1.101"},{"1":"4","2":"2","3":"101","4":"1","5":"5","6":"4.101","7":"2.101"},{"1":"5","2":"1","3":"101","4":"1","5":"5","6":"5.101","7":"1.101"},{"1":"5","2":"2","3":"101","4":"1","5":"3","6":"5.101","7":"2.101"},{"1":"1","2":"1","3":"102","4":"1","5":"3","6":"1.102","7":"1.102"},{"1":"1","2":"2","3":"102","4":"1","5":"4","6":"1.102","7":"2.102"},{"1":"2","2":"1","3":"102","4":"1","5":"2","6":"2.102","7":"1.102"},{"1":"2","2":"2","3":"102","4":"1","5":"2","6":"2.102","7":"2.102"},{"1":"3","2":"1","3":"102","4":"1","5":"2","6":"3.102","7":"1.102"},{"1":"3","2":"2","3":"102","4":"1","5":"3","6":"3.102","7":"2.102"},{"1":"4","2":"1","3":"102","4":"1","5":"3","6":"4.102","7":"1.102"},{"1":"4","2":"2","3":"102","4":"1","5":"5","6":"4.102","7":"2.102"},{"1":"5","2":"1","3":"102","4":"1","5":"1","6":"5.102","7":"1.102"},{"1":"5","2":"2","3":"102","4":"1","5":"2","6":"5.102","7":"2.102"},{"1":"1","2":"1","3":"103","4":"1","5":"5","6":"1.103","7":"1.103"},{"1":"1","2":"2","3":"103","4":"1","5":"4","6":"1.103","7":"2.103"},{"1":"2","2":"1","3":"103","4":"1","5":"4","6":"2.103","7":"1.103"},{"1":"2","2":"2","3":"103","4":"1","5":"4","6":"2.103","7":"2.103"},{"1":"3","2":"1","3":"103","4":"1","5":"5","6":"3.103","7":"1.103"},{"1":"3","2":"2","3":"103","4":"1","5":"5","6":"3.103","7":"2.103"},{"1":"4","2":"1","3":"103","4":"1","5":"5","6":"4.103","7":"1.103"},{"1":"4","2":"2","3":"103","4":"1","5":"5","6":"4.103","7":"2.103"},{"1":"5","2":"1","3":"103","4":"1","5":"5","6":"5.103","7":"1.103"},{"1":"5","2":"2","3":"103","4":"1","5":"5","6":"5.103","7":"2.103"},{"1":"1","2":"1","3":"104","4":"1","5":"5","6":"1.104","7":"1.104"},{"1":"1","2":"2","3":"104","4":"1","5":"5","6":"1.104","7":"2.104"},{"1":"2","2":"1","3":"104","4":"1","5":"2","6":"2.104","7":"1.104"},{"1":"2","2":"2","3":"104","4":"1","5":"2","6":"2.104","7":"2.104"},{"1":"3","2":"1","3":"104","4":"1","5":"5","6":"3.104","7":"1.104"},{"1":"3","2":"2","3":"104","4":"1","5":"5","6":"3.104","7":"2.104"},{"1":"4","2":"1","3":"104","4":"1","5":"5","6":"4.104","7":"1.104"},{"1":"4","2":"2","3":"104","4":"1","5":"5","6":"4.104","7":"2.104"},{"1":"5","2":"1","3":"104","4":"1","5":"1","6":"5.104","7":"1.104"},{"1":"5","2":"2","3":"104","4":"1","5":"4","6":"5.104","7":"2.104"},{"1":"1","2":"1","3":"105","4":"1","5":"5","6":"1.105","7":"1.105"},{"1":"1","2":"2","3":"105","4":"1","5":"5","6":"1.105","7":"2.105"},{"1":"2","2":"1","3":"105","4":"1","5":"5","6":"2.105","7":"1.105"},{"1":"2","2":"2","3":"105","4":"1","5":"5","6":"2.105","7":"2.105"},{"1":"3","2":"1","3":"105","4":"1","5":"5","6":"3.105","7":"1.105"},{"1":"3","2":"2","3":"105","4":"1","5":"5","6":"3.105","7":"2.105"},{"1":"4","2":"1","3":"105","4":"1","5":"5","6":"4.105","7":"1.105"},{"1":"4","2":"2","3":"105","4":"1","5":"5","6":"4.105","7":"2.105"},{"1":"5","2":"1","3":"105","4":"1","5":"5","6":"5.105","7":"1.105"},{"1":"5","2":"2","3":"105","4":"1","5":"5","6":"5.105","7":"2.105"},{"1":"1","2":"1","3":"106","4":"1","5":"1","6":"1.106","7":"1.106"},{"1":"1","2":"2","3":"106","4":"1","5":"5","6":"1.106","7":"2.106"},{"1":"2","2":"1","3":"106","4":"1","5":"2","6":"2.106","7":"1.106"},{"1":"2","2":"2","3":"106","4":"1","5":"5","6":"2.106","7":"2.106"},{"1":"3","2":"1","3":"106","4":"1","5":"2","6":"3.106","7":"1.106"},{"1":"3","2":"2","3":"106","4":"1","5":"5","6":"3.106","7":"2.106"},{"1":"4","2":"1","3":"106","4":"1","5":"1","6":"4.106","7":"1.106"},{"1":"4","2":"2","3":"106","4":"1","5":"5","6":"4.106","7":"2.106"},{"1":"5","2":"1","3":"106","4":"1","5":"1","6":"5.106","7":"1.106"},{"1":"5","2":"2","3":"106","4":"1","5":"5","6":"5.106","7":"2.106"},{"1":"1","2":"1","3":"107","4":"1","5":"1","6":"1.107","7":"1.107"},{"1":"1","2":"2","3":"107","4":"1","5":"3","6":"1.107","7":"2.107"},{"1":"2","2":"1","3":"107","4":"1","5":"2","6":"2.107","7":"1.107"},{"1":"2","2":"2","3":"107","4":"1","5":"2","6":"2.107","7":"2.107"},{"1":"3","2":"1","3":"107","4":"1","5":"2","6":"3.107","7":"1.107"},{"1":"3","2":"2","3":"107","4":"1","5":"3","6":"3.107","7":"2.107"},{"1":"4","2":"1","3":"107","4":"1","5":"2","6":"4.107","7":"1.107"},{"1":"4","2":"2","3":"107","4":"1","5":"3","6":"4.107","7":"2.107"},{"1":"5","2":"1","3":"107","4":"1","5":"1","6":"5.107","7":"1.107"},{"1":"5","2":"2","3":"107","4":"1","5":"3","6":"5.107","7":"2.107"},{"1":"1","2":"1","3":"108","4":"1","5":"5","6":"1.108","7":"1.108"},{"1":"1","2":"2","3":"108","4":"1","5":"5","6":"1.108","7":"2.108"},{"1":"2","2":"1","3":"108","4":"1","5":"5","6":"2.108","7":"1.108"},{"1":"2","2":"2","3":"108","4":"1","5":"5","6":"2.108","7":"2.108"},{"1":"3","2":"1","3":"108","4":"1","5":"5","6":"3.108","7":"1.108"},{"1":"3","2":"2","3":"108","4":"1","5":"4","6":"3.108","7":"2.108"},{"1":"4","2":"1","3":"108","4":"1","5":"5","6":"4.108","7":"1.108"},{"1":"4","2":"2","3":"108","4":"1","5":"5","6":"4.108","7":"2.108"},{"1":"5","2":"1","3":"108","4":"1","5":"5","6":"5.108","7":"1.108"},{"1":"5","2":"2","3":"108","4":"1","5":"3","6":"5.108","7":"2.108"},{"1":"1","2":"1","3":"109","4":"1","5":"5","6":"1.109","7":"1.109"},{"1":"1","2":"2","3":"109","4":"1","5":"5","6":"1.109","7":"2.109"},{"1":"2","2":"1","3":"109","4":"1","5":"5","6":"2.109","7":"1.109"},{"1":"2","2":"2","3":"109","4":"1","5":"5","6":"2.109","7":"2.109"},{"1":"3","2":"1","3":"109","4":"1","5":"5","6":"3.109","7":"1.109"},{"1":"3","2":"2","3":"109","4":"1","5":"5","6":"3.109","7":"2.109"},{"1":"4","2":"1","3":"109","4":"1","5":"5","6":"4.109","7":"1.109"},{"1":"4","2":"2","3":"109","4":"1","5":"5","6":"4.109","7":"2.109"},{"1":"5","2":"1","3":"109","4":"1","5":"5","6":"5.109","7":"1.109"},{"1":"5","2":"2","3":"109","4":"1","5":"5","6":"5.109","7":"2.109"},{"1":"1","2":"1","3":"110","4":"1","5":"5","6":"1.110","7":"1.110"},{"1":"1","2":"2","3":"110","4":"1","5":"5","6":"1.110","7":"2.110"},{"1":"2","2":"1","3":"110","4":"1","5":"5","6":"2.110","7":"1.110"},{"1":"2","2":"2","3":"110","4":"1","5":"5","6":"2.110","7":"2.110"},{"1":"3","2":"1","3":"110","4":"1","5":"5","6":"3.110","7":"1.110"},{"1":"3","2":"2","3":"110","4":"1","5":"5","6":"3.110","7":"2.110"},{"1":"4","2":"1","3":"110","4":"1","5":"5","6":"4.110","7":"1.110"},{"1":"4","2":"2","3":"110","4":"1","5":"5","6":"4.110","7":"2.110"},{"1":"5","2":"1","3":"110","4":"1","5":"5","6":"5.110","7":"1.110"},{"1":"5","2":"2","3":"110","4":"1","5":"5","6":"5.110","7":"2.110"},{"1":"1","2":"1","3":"111","4":"1","5":"4","6":"1.111","7":"1.111"},{"1":"1","2":"2","3":"111","4":"1","5":"5","6":"1.111","7":"2.111"},{"1":"2","2":"1","3":"111","4":"1","5":"5","6":"2.111","7":"1.111"},{"1":"2","2":"2","3":"111","4":"1","5":"5","6":"2.111","7":"2.111"},{"1":"3","2":"1","3":"111","4":"1","5":"5","6":"3.111","7":"1.111"},{"1":"3","2":"2","3":"111","4":"1","5":"5","6":"3.111","7":"2.111"},{"1":"4","2":"1","3":"111","4":"1","5":"5","6":"4.111","7":"1.111"},{"1":"4","2":"2","3":"111","4":"1","5":"5","6":"4.111","7":"2.111"},{"1":"5","2":"1","3":"111","4":"1","5":"3","6":"5.111","7":"1.111"},{"1":"5","2":"2","3":"111","4":"1","5":"5","6":"5.111","7":"2.111"},{"1":"1","2":"1","3":"112","4":"1","5":"4","6":"1.112","7":"1.112"},{"1":"1","2":"2","3":"112","4":"1","5":"5","6":"1.112","7":"2.112"},{"1":"2","2":"1","3":"112","4":"1","5":"3","6":"2.112","7":"1.112"},{"1":"2","2":"2","3":"112","4":"1","5":"5","6":"2.112","7":"2.112"},{"1":"3","2":"1","3":"112","4":"1","5":"5","6":"3.112","7":"1.112"},{"1":"3","2":"2","3":"112","4":"1","5":"5","6":"3.112","7":"2.112"},{"1":"4","2":"1","3":"112","4":"1","5":"5","6":"4.112","7":"1.112"},{"1":"4","2":"2","3":"112","4":"1","5":"5","6":"4.112","7":"2.112"},{"1":"5","2":"1","3":"112","4":"1","5":"5","6":"5.112","7":"1.112"},{"1":"5","2":"2","3":"112","4":"1","5":"5","6":"5.112","7":"2.112"},{"1":"1","2":"1","3":"113","4":"1","5":"5","6":"1.113","7":"1.113"},{"1":"1","2":"2","3":"113","4":"1","5":"5","6":"1.113","7":"2.113"},{"1":"2","2":"1","3":"113","4":"1","5":"5","6":"2.113","7":"1.113"},{"1":"2","2":"2","3":"113","4":"1","5":"5","6":"2.113","7":"2.113"},{"1":"3","2":"1","3":"113","4":"1","5":"5","6":"3.113","7":"1.113"},{"1":"3","2":"2","3":"113","4":"1","5":"5","6":"3.113","7":"2.113"},{"1":"4","2":"1","3":"113","4":"1","5":"5","6":"4.113","7":"1.113"},{"1":"4","2":"2","3":"113","4":"1","5":"5","6":"4.113","7":"2.113"},{"1":"5","2":"1","3":"113","4":"1","5":"5","6":"5.113","7":"1.113"},{"1":"5","2":"2","3":"113","4":"1","5":"5","6":"5.113","7":"2.113"},{"1":"1","2":"1","3":"114","4":"1","5":"1","6":"1.114","7":"1.114"},{"1":"1","2":"2","3":"114","4":"1","5":"1","6":"1.114","7":"2.114"},{"1":"2","2":"1","3":"114","4":"1","5":"2","6":"2.114","7":"1.114"},{"1":"2","2":"2","3":"114","4":"1","5":"2","6":"2.114","7":"2.114"},{"1":"3","2":"1","3":"114","4":"1","5":"2","6":"3.114","7":"1.114"},{"1":"3","2":"2","3":"114","4":"1","5":"1","6":"3.114","7":"2.114"},{"1":"4","2":"1","3":"114","4":"1","5":"5","6":"4.114","7":"1.114"},{"1":"4","2":"2","3":"114","4":"1","5":"5","6":"4.114","7":"2.114"},{"1":"5","2":"1","3":"114","4":"1","5":"2","6":"5.114","7":"1.114"},{"1":"5","2":"2","3":"114","4":"1","5":"3","6":"5.114","7":"2.114"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The study employed a factorial design in which each of the five
radiologists read and rated both the CINE and SE MRI images from all 114
cases. The original study variables in the <code>VanDyke</code> data
frame are summarized below along with two additional <code>case2</code>
and <code>case3</code> variables that represent hypothetical study
designs in which cases are nested within readers (<code>reader</code>)
and within imaging modalities (<code>treatment</code>),
respectively.</p>
<table>
<colgroup>
<col width="14%" />
<col width="85%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>reader</code></td>
<td align="left">unique identifiers for the five radiologists</td>
</tr>
<tr class="even">
<td align="left"><code>treatment</code></td>
<td align="left">identifiers for the imaging modality (1 = CINE MRI, 2 =
SE MRI)</td>
</tr>
<tr class="odd">
<td align="left"><code>case</code></td>
<td align="left">identifiers for the 114 cases</td>
</tr>
<tr class="even">
<td align="left"><code>truth</code></td>
<td align="left">indicator for thoracic aortic dissection (1 =
performed, 0 = not performed)</td>
</tr>
<tr class="odd">
<td align="left"><code>rating</code></td>
<td align="left">five-point ratings given to case images by the
readers</td>
</tr>
<tr class="even">
<td align="left"><code>case2</code></td>
<td align="left">example identifiers representing nesting of cases
within readers</td>
</tr>
<tr class="odd">
<td align="left"><code>case3</code></td>
<td align="left">example identifiers representing nesting of cases
within treatments</td>
</tr>
</tbody>
</table>
<p>Data from other studies may be analyzed with the package and should
follow the format of <code>VanDyke</code> with columns for reader,
treatment, and case identifiers as well as true event statuses and
reader ratings. The variable names, however, may be different.</p>
</div>
<div id="multi-reader-multi-case-analysis" class="section level1"
number="4">
<h1><span class="header-section-number">4</span> Multi-Reader Multi-Case
Analysis</h1>
<p>A multi-reader multi-case (MRMC) analysis, as the name suggests,
involves multiple readers of multiple cases to compare reader
performance metrics across two or more diagnostic tests. An MRMC
analysis can be performed with a call to the <code>mrmc()</code>
function to specify a reader performance metric, study variables and
observations, and covariance estimation method.</p>
<blockquote>
<p><strong>MRMC Function</strong></p>
<p><code>mrmc(response, test, reader, case, data, cov = jackknife)</code></p>
<p><em>Description</em></p>
<p>Returns an <code>mrmc</code> class object of data that can be used to
estimate and compare reader performance metrics in a multi-reader
multi-case statistical analysis.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>response</code>: object defining true case statuses,
corresponding reader ratings, and a reader performance metric to compute
on them.</li>
<li><code>test</code>, <code>reader</code>, <code>case</code>: variables
containing the test, reader, and case identifiers for the
<code>response</code> observations.</li>
<li><code>data</code>: data frame containing the response and identifier
variables.</li>
<li><code>cov</code>: function <code>jackknife</code>,
<code>unbiased</code>, or <code>DeLong</code> to estimate reader
performance metric covariances.</li>
</ul>
</blockquote>
<p>The response variable in the <code>mrmc()</code> specification is
defined with one of the performance metrics described in the following
sections. Results from <code>mrmc()</code> can be displayed with
<code>print()</code> and passed to <code>summary()</code> for
statistical comparisons of the diagnostic tests. The summary call
produces ANOVA results from a global test of equality of ROC AUC means
across all tests and statistical tests of pairwise differences, along
with confidence intervals for the differences and intervals for
individual tests.</p>
<blockquote>
<p><strong>MRMC Summary Function</strong></p>
<p><code>summary(object, conf.level = 0.95)</code></p>
<p><em>Description</em></p>
<p>Returns a <code>summary.mrmc</code> class object of statistical
results from a multi-reader multi-case analysis.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>object</code>: results from <code>mrmc()</code>.</li>
<li><code>conf.level</code>: confidence level for confidence
intervals.</li>
</ul>
</blockquote>
<div id="performance-metrics" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Performance
Metrics</h2>
<div id="area-under-the-roc-curve" class="section level3"
number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Area Under the ROC
Curve</h3>
<p>Area under the ROC curve is a measure of concordance between numeric
reader ratings and true binary case statuses. It provides an estimate of
the probability that a randomly selected positive case will have a
higher rating than a negative case. ROC AUC values range from 0 to 1,
with 0.5 representing no concordance and 1 perfect concordance. AUC can
be computed with the functions described below for binormal, binormal
likelihood-ratio, and empirical ROC curves. Empirical curves are also
referred to as trapezoidal. The functions also support calculation of
partial AUC over a range of sensitivities or specificities.</p>
<blockquote>
<p><strong>ROC AUC Functions</strong></p>
<p><code>binormal_auc(truth, rating, partial = FALSE, min = 0, max = 1, normalize = FALSE)</code><br />
<code>binormalLR_auc(truth, rating, partial = FALSE, min = 0, max = 1, normalize = FALSE)</code><br />
<code>empirical_auc(truth, rating, partial = FALSE, min = 0, max = 1, normalize = FALSE)</code><br />
<code>trapezoidal_auc(truth, rating, partial = FALSE, min = 0, max = 1, normalize = FALSE)</code></p>
<p><em>Description</em></p>
<p>Returns computed area under the receiver operating character curve
estimated with a binormal model (<code>binormal_auc</code>), binormal
likelihood-ratio model (<code>binormalLR_auc</code>), or empirically
(<code>empirical_auc</code> or <code>trapezoidal_auc</code>).</p>
<p><em>Arguments</em></p>
<ul>
<li><code>truth</code>: vector of true binary case statuses, with
positive status taken to be the highest level.</li>
<li><code>rating</code>: numeric vector of case ratings.</li>
<li><code>partial</code>: character string <code>"sensitivity"</code> or
<code>"specificity"</code> for calculation of partial AUC, or
<code>FALSE</code> for full AUC. Partial matching of the character
strings is allowed. A value of <code>"specificity"</code> results in
area under the ROC curve between the given <code>min</code> and
<code>max</code> specificity values, whereas <code>"sensitivity"</code>
results in area to the right of the curve between the given sensitivity
values.</li>
<li><code>min</code>, <code>max</code>: minimum and maximum sensitivity
or specificity values over which to calculate partial AUC.</li>
<li><code>normalize</code>: logical indicating whether partial AUC is
divided by the interval width (<code>max - min</code>) over which it is
calculated.</li>
</ul>
</blockquote>
<p>In the example below, <code>mrmc()</code> is called to compare CINE
MRI and SE MRI treatments in an MRMC analysis of areas under binormal
ROC curves computed for the readers of cases in the VanDyke study.</p>
<pre class="r"><code>## Compare ROC AUC treatment means for the VanDyke example
est &lt;- mrmc(
  binormal_auc(truth, rating), treatment, reader, case, data = VanDyke
)</code></pre>
<p>The <code>print()</code> function can be applied to
<code>mrmc()</code> output to display information about the reader
performance metrics, including the</p>
<ul>
<li>value of variable <code>truth</code> (1) defining positive case
status,</li>
<li>estimated performance metric values (<code>data$binormal_auc</code>)
for each test (<code>$treatment</code>) and reader
(<code>$reader</code>),</li>
<li>number of cases read at each level of the factors (<code>N</code>),
and</li>
<li>error variance <span
class="math inline">\(\sigma^2_\epsilon\)</span> and covariances <span
class="math inline">\(\text{Cov}_1\)</span>, <span
class="math inline">\(\text{Cov}_2\)</span>, and <span
class="math inline">\(\text{Cov}_3\)</span>.</li>
</ul>
<details>
<summary>
<strong>Show MRMC Performance Metrics</strong>
</summary>
<pre class="r"><code>print(est)
#&gt; Call:
#&gt; mrmc(response = binormal_auc(truth, rating), test = treatment, 
#&gt;     reader = reader, case = case, data = VanDyke)
#&gt; 
#&gt; Positive truth status: 1 
#&gt; 
#&gt; Response metric data:
#&gt; 
#&gt; # A tibble: 10 × 2
#&gt;        N data$binormal_auc $treatment $reader
#&gt;    &lt;dbl&gt;             &lt;dbl&gt; &lt;fct&gt;      &lt;fct&gt;  
#&gt;  1   114             0.933 1          1      
#&gt;  2   114             0.890 1          2      
#&gt;  3   114             0.929 1          3      
#&gt;  4   114             0.970 1          4      
#&gt;  5   114             0.833 1          5      
#&gt;  6   114             0.951 2          1      
#&gt;  7   114             0.935 2          2      
#&gt;  8   114             0.928 2          3      
#&gt;  9   114             1     2          4      
#&gt; 10   114             0.945 2          5      
#&gt; 
#&gt; ANOVA Table:
#&gt; 
#&gt;                  Df    Sum Sq   Mean Sq
#&gt; treatment         1 0.0041142 0.0041142
#&gt; reader            4 0.0104325 0.0026081
#&gt; treatment:reader  4 0.0037916 0.0009479
#&gt; 
#&gt; 
#&gt; Obuchowski-Rockette error variance and covariance estimates:
#&gt; 
#&gt;           Estimate Correlation
#&gt; Error 0.0010790500          NA
#&gt; Cov1  0.0003125013   0.2896078
#&gt; Cov2  0.0003115986   0.2887713
#&gt; Cov3  0.0001937688   0.1795735</code></pre>
</details>
<p>
<p>MRMC statistical tests are performed with a call to
<code>summary()</code>. Results include a test of the global null
hypothesis that performances are equal across all diagnostic tests,
tests of their pairwise mean differences, and estimated mean
performances for each one.</p>
<details>
<summary>
<strong>Show MRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Multi-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke
#&gt; Factor types: Random Readers and Random Cases
#&gt; Covariance method: jackknife
#&gt; 
#&gt; Experimental design: factorial 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt;                      Estimate Correlation
#&gt; reader           0.0007113799          NA
#&gt; treatment:reader 0.0002991713          NA
#&gt; Error            0.0010790500          NA
#&gt; Cov1             0.0003125013   0.2896078
#&gt; Cov2             0.0003115986   0.2887713
#&gt; Cov3             0.0001937688   0.1795735
#&gt; 
#&gt; 
#&gt; ANOVA global test of equal treatment binormal_auc:
#&gt;         MS(T)      MS(T:R)         Cov2         Cov3 Denominator        F df1
#&gt; 1 0.004114188 0.0009478901 0.0003115986 0.0001937688 0.001537039 2.676697   1
#&gt;        df2   p-value
#&gt; 1 10.51753 0.1313668
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment binormal_auc pairwise differences:
#&gt;   Comparison    Estimate     StdErr       df    CI.Lower    CI.Upper         t
#&gt; 1      1 - 2 -0.04056692 0.02479548 10.51753 -0.09544840  0.01431455 -1.636061
#&gt;     p-value
#&gt; 1 0.1313668
#&gt; 
#&gt; 
#&gt; 95% treatment binormal_auc CIs (each analysis based only on data for the
#&gt; specified treatment):
#&gt;    Estimate        MS(R)         Cov2     StdErr       df  CI.Lower  CI.Upper
#&gt; 1 0.9109867 0.0027417526 0.0004612201 0.03177374 13.55866 0.8426301 0.9793433
#&gt; 2 0.9515536 0.0008142524 0.0001619772 0.01802298 15.91432 0.9133299 0.9897774</code></pre>
</details>
<p>
<p>ROC curves estimated by <code>mrmc()</code> can be displayed with
<code>plot()</code> and their parameters extracted with
<code>parameters()</code>.</p>
<details>
<summary>
<strong>Show MRMC ROC Curves</strong>
</summary>
<pre class="r"><code>plot(est)</code></pre>
<img src="using_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" />
</details>
<details>
<summary>
<strong>Show MRMC ROC Curve Parameters</strong>
</summary>
<pre class="r"><code>print(parameters(est))
#&gt; # A tibble: 10 × 3
#&gt;    Group$reader $treatment      a     b
#&gt;    &lt;fct&gt;        &lt;fct&gt;       &lt;dbl&gt; &lt;dbl&gt;
#&gt;  1 1            1            1.70 0.537
#&gt;  2 2            1            1.40 0.561
#&gt;  3 3            1            1.74 0.635
#&gt;  4 4            1            1.93 0.202
#&gt;  5 5            1            1.06 0.464
#&gt;  6 1            2            1.85 0.503
#&gt;  7 2            2            1.66 0.447
#&gt;  8 3            2            1.62 0.488
#&gt;  9 4            2          Inf    1    
#&gt; 10 5            2            1.73 0.422</code></pre>
</details>
<p>
</div>
<div id="roc-curve-expected-utility" class="section level3"
number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> ROC Curve Expected
Utility</h3>
<p>As an alternative to AUC as a summary of ROC curves, Abbey et al.
<span class="citation">(2013)</span> propose an expected utility metric
defined as <span class="math display">\[
\text{EU} = \max_\text{FPR}(\text{TPR}(\text{FPR}) - \beta \times
\text{FPR}),
\]</span> where <span
class="math inline">\(\text{TPR}(\text{FPR})\)</span> are true positive
rates on the ROC curve, and FPR are false positive rates ranging from 0
to 1.</p>
<blockquote>
<p><strong>ROC Curve Expected Utility Functions</strong></p>
<p><code>binormal_eu(truth, rating, slope = 1)</code><br />
<code>binormalLR_eu(truth, rating, slope = 1)</code><br />
<code>empirical_eu(truth, rating, slope = 1)</code><br />
<code>trapezoidal_eu(truth, rating, slope = 1)</code></p>
<p><em>Description</em></p>
<p>Returns expected utility of an ROC curve.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>truth</code>: vector of true binary case statuses, with
positive status taken to be the highest level.</li>
<li><code>rating</code>: numeric vector of case ratings.</li>
<li><code>slope</code>: numeric slope (<span
class="math inline">\(\beta\)</span>) at which to compute expected
utility.</li>
</ul>
</blockquote>
</div>
<div id="roc-curve-sensitivity-and-specificity" class="section level3"
number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> ROC Curve
Sensitivity and Specificity</h3>
<p>Functions are provided to extract sensitivity from an ROC curve for a
given specificity and vice versa.</p>
<blockquote>
<p><strong>ROC Curve Sensitivity and Specificity Functions</strong></p>
<p><code>binormal_sens(truth, rating, spec)</code><br />
<code>binormal_spec(truth, rating, sens)</code><br />
<code>binormalLR_sens(truth, rating, spec)</code><br />
<code>binormalLR_spec(truth, rating, sens)</code><br />
<code>empirical_sens(truth, rating, spec)</code><br />
<code>empirical_spec(truth, rating, sens)</code><br />
<code>trapezoidal_sens(truth, rating, spec)</code><br />
<code>trapezoidal_spec(truth, rating, sens)</code></p>
<p><em>Description</em></p>
<p>Returns the sensitivity/specificity from an ROC curve at a specified
specificity/sensitivity.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>truth</code>: vector of true binary case statuses, with
positive status taken to be the highest level.</li>
<li><code>rating</code>: numeric vector of case ratings.</li>
<li><code>spec</code>, <code>sens</code>: specificity/sensitivity on the
ROC curve at which to return sensitivity/specificity.</li>
</ul>
</blockquote>
</div>
<div id="binary-metrics" class="section level3" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> Binary Metrics</h3>
<p>Metrics for binary reader ratings are also available.</p>
<blockquote>
<p><strong>Sensitivity and Specificity Functions</strong></p>
<p><code>binary_sens(truth, rating)</code><br />
<code>binary_spec(truth, rating)</code></p>
<p><em>Description</em></p>
<p>Returns the sensitivity or specificity.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>truth</code>: vector of true binary case statuses, with
positive status taken to be the highest level.</li>
<li><code>rating</code>: factor or numeric vector of 0-1 binary
ratings.</li>
</ul>
</blockquote>
<pre class="r"><code>## Compare sensitivity for binary classification
VanDyke$binary_rating &lt;- VanDyke$rating &gt;= 3
est &lt;- mrmc(
  binary_sens(truth, binary_rating), treatment, reader, case, data = VanDyke
)</code></pre>
<details>
<summary>
<strong>Show MRMC Performance Metrics</strong>
</summary>
<pre class="r"><code>print(est)
#&gt; Call:
#&gt; mrmc(response = binary_sens(truth, binary_rating), test = treatment, 
#&gt;     reader = reader, case = case, data = VanDyke)
#&gt; 
#&gt; Positive truth status: 1 
#&gt; 
#&gt; Response metric data:
#&gt; 
#&gt; # A tibble: 10 × 2
#&gt;        N data$binary_sens $treatment $reader
#&gt;    &lt;dbl&gt;            &lt;dbl&gt; &lt;fct&gt;      &lt;fct&gt;  
#&gt;  1    45            0.889 1          1      
#&gt;  2    45            0.778 1          2      
#&gt;  3    45            0.822 1          3      
#&gt;  4    45            0.933 1          4      
#&gt;  5    45            0.689 1          5      
#&gt;  6    45            0.978 2          1      
#&gt;  7    45            0.822 2          2      
#&gt;  8    45            0.911 2          3      
#&gt;  9    45            1     2          4      
#&gt; 10    45            0.889 2          5      
#&gt; 
#&gt; ANOVA Table:
#&gt; 
#&gt;                  Df   Sum Sq   Mean Sq
#&gt; treatment         1 0.023901 0.0239012
#&gt; reader            4 0.049679 0.0124198
#&gt; treatment:reader  4 0.007210 0.0018025
#&gt; 
#&gt; 
#&gt; Obuchowski-Rockette error variance and covariance estimates:
#&gt; 
#&gt;           Estimate Correlation
#&gt; Error 0.0023681257          NA
#&gt; Cov1  0.0009943883   0.4199052
#&gt; Cov2  0.0010145903   0.4284360
#&gt; Cov3  0.0006604938   0.2789100</code></pre>
</details>
<details>
<summary>
<strong>Show MRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Multi-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke
#&gt; Factor types: Random Readers and Random Cases
#&gt; Covariance method: jackknife
#&gt; 
#&gt; Experimental design: factorial 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt;                      Estimate Correlation
#&gt; reader           0.0049747475          NA
#&gt; treatment:reader 0.0007828283          NA
#&gt; Error            0.0023681257          NA
#&gt; Cov1             0.0009943883   0.4199052
#&gt; Cov2             0.0010145903   0.4284360
#&gt; Cov3             0.0006604938   0.2789100
#&gt; 
#&gt; 
#&gt; ANOVA global test of equal treatment binary_sens:
#&gt;        MS(T)     MS(T:R)       Cov2         Cov3 Denominator        F df1
#&gt; 1 0.02390123 0.001802469 0.00101459 0.0006604938 0.003572952 6.689493   1
#&gt;        df2    p-value
#&gt; 1 15.71732 0.02008822
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment binary_sens pairwise differences:
#&gt;   Comparison    Estimate     StdErr       df   CI.Lower   CI.Upper         t
#&gt; 1      1 - 2 -0.09777778 0.03780451 15.71732 -0.1780371 -0.0175185 -2.586405
#&gt;      p-value
#&gt; 1 0.02008822
#&gt; 
#&gt; 
#&gt; 95% treatment binary_sens CIs (each analysis based only on data for the
#&gt; specified treatment):
#&gt;    Estimate       MS(R)        Cov2     StdErr        df  CI.Lower  CI.Upper
#&gt; 1 0.8222222 0.009135802 0.001646465 0.05893747 14.456811 0.6961876 0.9482568
#&gt; 2 0.9200000 0.005086420 0.000382716 0.03741657  7.575855 0.8328691 1.0000000</code></pre>
</details>
<p>
</div>
</div>
<div id="covariance-estimation-methods" class="section level2"
number="4.2">
<h2><span class="header-section-number">4.2</span> Covariance Estimation
Methods</h2>
<p>Special statistical methods are needed in MRMC analyses to estimate
covariances between performance metrics from different readers and tests
when cases are treated as a random sample and are rated by more than one
reader or evaluated with more than one test. For this estimation, the
package provides the DeLong method <span class="citation">(DeLong,
DeLong, and Clarke-Pearson 1988)</span>, jackknifing <span
class="citation">(Efron 1982)</span>, and an unbiased method <span
class="citation">(Gallas, Pennello, and Meyers 2007)</span>. The
applicability of each depends on the study design as well as the
performance metric being analyzed. DeLong is appropriate for a balanced
factorial design and empirical ROC AUC, jackknifing for any design and
metric, and unbiased for any design and empirical ROC AUC.</p>
<table style="width:100%;">
<colgroup>
<col width="31%" />
<col width="20%" />
<col width="27%" />
<col width="21%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Covariance Method</th>
<th align="left">Study Design</th>
<th align="left">Metric</th>
<th align="left">Function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DeLong</td>
<td align="left">Factorial</td>
<td align="left">Empirical ROC AUC</td>
<td align="left"><code>DeLong()</code></td>
</tr>
<tr class="even">
<td align="left">Jackknife</td>
<td align="left">Any</td>
<td align="left">Any</td>
<td align="left"><code>jackknife()</code></td>
</tr>
<tr class="odd">
<td align="left">Unbiased</td>
<td align="left">Any</td>
<td align="left">Empirical ROC AUC</td>
<td align="left"><code>unbiased()</code></td>
</tr>
</tbody>
</table>
<p>Jackknifing is the default covariance method for <code>mrmc()</code>.
Others can be specified with its <code>cov</code> argument.</p>
<pre class="r"><code>## DeLong method
est &lt;- mrmc(
  empirical_auc(truth, rating), treatment, reader, case, data = VanDyke,
  cov = DeLong
)</code></pre>
<details>
<summary>
<strong>Show MRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Multi-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke
#&gt; Factor types: Random Readers and Random Cases
#&gt; Covariance method: DeLong
#&gt; 
#&gt; Experimental design: factorial 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt;                      Estimate Correlation
#&gt; reader           0.0015364254          NA
#&gt; treatment:reader 0.0002045840          NA
#&gt; Error            0.0007921325          NA
#&gt; Cov1             0.0003420090   0.4317573
#&gt; Cov2             0.0003395265   0.4286234
#&gt; Cov3             0.0002358497   0.2977402
#&gt; 
#&gt; 
#&gt; ANOVA global test of equal treatment empirical_auc:
#&gt;         MS(T)      MS(T:R)         Cov2         Cov3 Denominator        F df1
#&gt; 1 0.004796171 0.0005510306 0.0003395265 0.0002358497 0.001069415 4.484854   1
#&gt;        df2    p-value
#&gt; 1 15.06611 0.05123303
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment empirical_auc pairwise differences:
#&gt;   Comparison    Estimate    StdErr       df      CI.Lower      CI.Upper
#&gt; 1      1 - 2 -0.04380032 0.0206825 15.06611 -0.0878671960  0.0002665519
#&gt;           t    p-value
#&gt; 1 -2.117747 0.05123303
#&gt; 
#&gt; 
#&gt; 95% treatment empirical_auc CIs (each analysis based only on data for the
#&gt; specified treatment):
#&gt;    Estimate       MS(R)         Cov2     StdErr       df  CI.Lower  CI.Upper
#&gt; 1 0.8970370 0.003082629 0.0004775239 0.03307642 12.59597 0.8253461 0.9687280
#&gt; 2 0.9408374 0.001304602 0.0002015292 0.02150464 12.56530 0.8942155 0.9874592</code></pre>
</details>
<p>
<pre class="r"><code>## Unbiased method
est &lt;- mrmc(
  empirical_auc(truth, rating), treatment, reader, case, data = VanDyke,
  cov = unbiased
)</code></pre>
<details>
<summary>
<strong>Show MRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Multi-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke
#&gt; Factor types: Random Readers and Random Cases
#&gt; Covariance method: unbiased
#&gt; 
#&gt; Experimental design: factorial 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt;                      Estimate Correlation
#&gt; reader           0.0015365290          NA
#&gt; treatment:reader 0.0002077588          NA
#&gt; Error            0.0007883925          NA
#&gt; Cov1             0.0003416706   0.4333762
#&gt; Cov2             0.0003390650   0.4300713
#&gt; Cov3             0.0002356148   0.2988547
#&gt; 
#&gt; 
#&gt; ANOVA global test of equal treatment empirical_auc:
#&gt;         MS(T)      MS(T:R)        Cov2         Cov3 Denominator        F df1
#&gt; 1 0.004796171 0.0005510306 0.000339065 0.0002356148 0.001068281 4.489614   1
#&gt;        df2   p-value
#&gt; 1 15.03418 0.0511618
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment empirical_auc pairwise differences:
#&gt;   Comparison    Estimate     StdErr       df      CI.Lower      CI.Upper
#&gt; 1      1 - 2 -0.04380032 0.02067154 15.03418 -0.0878519409  0.0002512968
#&gt;           t   p-value
#&gt; 1 -2.118871 0.0511618
#&gt; 
#&gt; 
#&gt; 95% treatment empirical_auc CIs (each analysis based only on data for the
#&gt; specified treatment):
#&gt;    Estimate       MS(R)         Cov2    StdErr       df  CI.Lower  CI.Upper
#&gt; 1 0.8970370 0.003082629 0.0004771788 0.0330712 12.58802 0.8253526 0.9687214
#&gt; 2 0.9408374 0.001304602 0.0002009512 0.0214912 12.53391 0.8942323 0.9874424</code></pre>
</details>
<p>
</div>
<div id="fixed-factors" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Fixed Factors</h2>
<p>By default, readers and cases are treated as random effects by
<code>mrmc()</code>. Random effects are the appropriate designations
when inference is intended for the larger population from which study
readers and cases are considered to be a random sample. Either, but not
both, can be specified as fixed effects with the <code>fixed()</code>
function in applications where study readers or cases make up the entire
group to which inference is intended. When readers are designated as
fixed, <code>mrmc()</code> test results additionally include
reader-specific pairwise comparisons of the diagnostic tests as well as
mean estimates of the performance metric for each reader-test
combination.</p>
<pre class="r"><code>## Fixed readers
est &lt;- mrmc(
  empirical_auc(truth, rating), treatment, fixed(reader), case, data = VanDyke
)</code></pre>
<details>
<summary>
<strong>Show MRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Multi-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke
#&gt; Factor types: Fixed Readers and Random Cases
#&gt; Covariance method: jackknife
#&gt; 
#&gt; Experimental design: factorial 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt;                      Estimate Correlation
#&gt; reader           0.0015349993          NA
#&gt; treatment:reader 0.0002004025          NA
#&gt; Error            0.0008022883          NA
#&gt; Cov1             0.0003466137   0.4320314
#&gt; Cov2             0.0003440748   0.4288668
#&gt; Cov3             0.0002390284   0.2979333
#&gt; 
#&gt; 
#&gt; ANOVA global test of equal treatment empirical_auc:
#&gt;         MS(T)         Cov1         Cov2         Cov3  Denominator       X2 df
#&gt; 1 0.004796171 0.0003466137 0.0003440748 0.0002390284 0.0008758604 5.475953  1
#&gt;      p-value
#&gt; 1 0.01927984
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment empirical_auc pairwise differences:
#&gt;   Comparison    Estimate     StdErr    CI.Lower    CI.Upper         z
#&gt; 1      1 - 2 -0.04380032 0.01871748 -0.08048591 -0.00711473 -2.340075
#&gt;      p-value
#&gt; 1 0.01927984
#&gt; 
#&gt; 
#&gt; 95% treatment empirical_auc CIs (each analysis based only on data for the
#&gt; specified treatment):
#&gt;    Estimate   Var(Error)         Cov2     StdErr  CI.Lower  CI.Upper
#&gt; 1 0.8970370 0.0010141028 0.0004839618 0.02428971 0.8494301 0.9446440
#&gt; 2 0.9408374 0.0005904738 0.0002041879 0.01677632 0.9079564 0.9737183
#&gt; 
#&gt; 
#&gt; Reader-specific 95% CIs and tests for empirical_auc pairwise differences (each
#&gt; analysis based only on data for the specified reader):
#&gt;   Reader Comparison    Estimate     StdErr     CI.Lower     CI.Upper          z
#&gt; 1      1      1 - 2 -0.02818035 0.02551213 -0.078183215  0.021822507 -1.1045864
#&gt; 2      2      1 - 2 -0.04653784 0.02630183 -0.098088476  0.005012792 -1.7693768
#&gt; 3      3      1 - 2 -0.01787440 0.03120965 -0.079044180  0.043295388 -0.5727202
#&gt; 4      4      1 - 2 -0.02624799 0.01729129 -0.060138290  0.007642316 -1.5179891
#&gt; 5      5      1 - 2 -0.10016103 0.04405746 -0.186512066 -0.013809995 -2.2734182
#&gt;      p-value
#&gt; 1 0.26933885
#&gt; 2 0.07683102
#&gt; 3 0.56683414
#&gt; 4 0.12901715
#&gt; 5 0.02300099
#&gt; 
#&gt; 
#&gt; Single reader 95% CIs:
#&gt;    empirical_auc treatment reader       StdErr  CI.Lower  CI.Upper
#&gt; 1      0.9196457         1      1 0.0301255164 0.8606008 0.9786907
#&gt; 2      0.8587762         1      2 0.0363753335 0.7874818 0.9300705
#&gt; 3      0.9038647         1      3 0.0282594118 0.8484773 0.9592522
#&gt; 4      0.9731079         1      4 0.0173388332 0.9391244 1.0000000
#&gt; 5      0.8297907         1      5 0.0417201720 0.7480206 0.9115607
#&gt; 6      0.9478261         2      1 0.0221416887 0.9044292 0.9912230
#&gt; 7      0.9053140         2      2 0.0298151099 0.8468775 0.9637506
#&gt; 8      0.9217391         2      3 0.0297673065 0.8633963 0.9800820
#&gt; 9      0.9993559         2      4 0.0007213348 0.9979421 1.0000000
#&gt; 10     0.9299517         2      5 0.0262023046 0.8785961 0.9813073</code></pre>
</details>
<p>
<pre class="r"><code>## Fixed cases
est &lt;- mrmc(
  empirical_auc(truth, rating), treatment, reader, fixed(case), data = VanDyke
)</code></pre>
<details>
<summary>
<strong>Show MRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Multi-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke
#&gt; Factor types: Random Readers and Fixed Cases
#&gt; Experimental design: factorial 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt; Not applicable because cases are fixed
#&gt; 
#&gt; 
#&gt; ANOVA global test of equal treatment empirical_auc:
#&gt;         MS(T)      MS(T:R)     F df1 df2    p-value
#&gt; 1 0.004796171 0.0005510306 8.704   1   4 0.04195875
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment empirical_auc pairwise differences:
#&gt;   Comparison    Estimate df     StdErr    CI.Lower    CI.Upper         t
#&gt; 1      1 - 2 -0.04380032  4 0.01484629 -0.08502022 -0.00258042 -2.950254
#&gt;      p-value
#&gt; 1 0.04195875
#&gt; 
#&gt; 
#&gt; 95% treatment empirical_auc CIs (each analysis based only on data for the
#&gt; specified treatment):
#&gt;    Estimate       MS(R)     StdErr df  CI.Lower  CI.Upper
#&gt; 1 0.8970370 0.003082629 0.02482994  4 0.8280981 0.9659760
#&gt; 2 0.9408374 0.001304602 0.01615303  4 0.8959894 0.9856854</code></pre>
</details>
<p>
</div>
<div id="study-designs" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Study Designs</h2>
<p><strong>MRMCaov</strong> supports factorial, nested, and partially
paired study designs. In a factorial design, one set of cases is
evaluated by all readers and tests. This is the design employed by the
VanDyke study as indicated by its dataset <code>case</code> identifier
values which appear within each combination of the <code>reader</code>
and <code>treatment</code> identifiers. Designs in which a different set
of cases is evaluated by each reader or with each test can be specified
with unique codings of case identifiers within the corresponding nesting
factor. Example codings for these two nested designs are included in the
<code>VanDyke</code> dataset as <code>case2</code> and
<code>case3</code>. The <code>case2</code> identifiers differ from
reader to reader and thus represent a study design in which cases are
nested within readers. Likewise, the <code>case3</code> identifiers
differ by test and are an example design of cases nested within tests.
Additionally, the package supports partially paired designs in which
ratings may not be available on all cases for some readers or tests;
e.g., as a result of missing values. Nested and partially paired designs
require specification of jackknife (default) or unbiased as the
covariance estimation method.</p>
<pre><code>#&gt; Case identifier codings for factorial and nested study designs
#&gt;            Observation
#&gt; Factor      1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17 
#&gt;   reader    1   1   2   2   3   3   4   4   5   5   1   1   2   2   3   3   4  
#&gt;   treatment 1   2   1   2   1   2   1   2   1   2   1   2   1   2   1   2   1  
#&gt;   case      1   1   1   1   1   1   1   1   1   1   2   2   2   2   2   2   2  
#&gt;   case2     1.1 1.1 2.1 2.1 3.1 3.1 4.1 4.1 5.1 5.1 1.2 1.2 2.2 2.2 3.2 3.2 4.2
#&gt;   case3     1.1 2.1 1.1 2.1 1.1 2.1 1.1 2.1 1.1 2.1 1.2 2.2 1.2 2.2 1.2 2.2 1.2
#&gt;            Observation
#&gt; Factor      18  19  20  21  22  23  24  25  26  27  28  29  30 
#&gt;   reader    4   5   5   1   1   2   2   3   3   4   4   5   5  
#&gt;   treatment 2   1   2   1   2   1   2   1   2   1   2   1   2  
#&gt;   case      2   2   2   3   3   3   3   3   3   3   3   3   3  
#&gt;   case2     4.2 5.2 5.2 1.3 1.3 2.3 2.3 3.3 3.3 4.3 4.3 5.3 5.3
#&gt;   case3     2.2 1.2 2.2 1.3 2.3 1.3 2.3 1.3 2.3 1.3 2.3 1.3 2.3
#&gt; ... with 1110 more observations</code></pre>
<pre class="r"><code>## Cases nested within readers
est &lt;- mrmc(
  empirical_auc(truth, rating), treatment, reader, case2, data = VanDyke
)</code></pre>
<details>
<summary>
<strong>Show MRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Multi-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke
#&gt; Factor types: Random Readers and Random Cases
#&gt; Covariance method: jackknife
#&gt; 
#&gt; Experimental design: cases nested within reader 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt;                      Estimate Correlation
#&gt; reader           1.293517e-03          NA
#&gt; treatment:reader 9.213005e-05          NA
#&gt; Error            8.079682e-04          NA
#&gt; Cov1             3.490676e-04   0.4320314
#&gt; Cov2             0.000000e+00   0.0000000
#&gt; Cov3             0.000000e+00   0.0000000
#&gt; 
#&gt; 
#&gt; ANOVA global test of equal treatment empirical_auc:
#&gt;         MS(T)      MS(T:R) Cov2 Cov3  Denominator     F df1 df2    p-value
#&gt; 1 0.004796171 0.0005510306    0    0 0.0005510306 8.704   1   4 0.04195875
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment empirical_auc pairwise differences:
#&gt;   Comparison    Estimate     StdErr df    CI.Lower    CI.Upper         t
#&gt; 1      1 - 2 -0.04380032 0.01484629  4 -0.08502022 -0.00258042 -2.950254
#&gt;      p-value
#&gt; 1 0.04195875
#&gt; 
#&gt; 
#&gt; 95% treatment empirical_auc CIs (each analysis based only on data for the
#&gt; specified treatment):
#&gt;    Estimate       MS(R) Cov2     StdErr df  CI.Lower  CI.Upper
#&gt; 1 0.8970370 0.003082629    0 0.02482994  4 0.8280981 0.9659760
#&gt; 2 0.9408374 0.001304602    0 0.01615303  4 0.8959894 0.9856854</code></pre>
</details>
<p>
<pre class="r"><code>## Cases nested within tests
est &lt;- mrmc(
  empirical_auc(truth, rating), treatment, reader, case3, data = VanDyke
)</code></pre>
<details>
<summary>
<strong>Show MRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Multi-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke
#&gt; Factor types: Random Readers and Random Cases
#&gt; Covariance method: jackknife
#&gt; 
#&gt; Experimental design: cases nested within treatment 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt;                      Estimate Correlation
#&gt; reader           1.642585e-03          NA
#&gt; treatment:reader 9.078969e-05          NA
#&gt; Error            8.058382e-04          NA
#&gt; Cov1             0.000000e+00   0.0000000
#&gt; Cov2             3.455973e-04   0.4288668
#&gt; Cov3             0.000000e+00   0.0000000
#&gt; 
#&gt; 
#&gt; ANOVA global test of equal treatment empirical_auc:
#&gt;         MS(T)      MS(T:R)         Cov2 Cov3 Denominator        F df1      df2
#&gt; 1 0.004796171 0.0005510306 0.0003455973    0 0.002279017 2.104491   1 68.42325
#&gt;     p-value
#&gt; 1 0.1514363
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment empirical_auc pairwise differences:
#&gt;   Comparison    Estimate     StdErr       df    CI.Lower    CI.Upper         t
#&gt; 1      1 - 2 -0.04380032 0.03019283 68.42325 -0.10404242  0.01644178 -1.450686
#&gt;     p-value
#&gt; 1 0.1514363
#&gt; 
#&gt; 
#&gt; 95% treatment empirical_auc CIs (each analysis based only on data for the
#&gt; specified treatment):
#&gt;    Estimate       MS(R)         Cov2     StdErr       df  CI.Lower  CI.Upper
#&gt; 1 0.8970370 0.003082629 0.0004861032 0.03320586 12.79430 0.8251827 0.9688914
#&gt; 2 0.9408374 0.001304602 0.0002050913 0.02158730 12.75962 0.8941114 0.9875634</code></pre>
</details>
<p>
</div>
</div>
<div id="single-reader-multi-case-analysis" class="section level1"
number="5">
<h1><span class="header-section-number">5</span> Single-Reader
Multi-Case Analysis</h1>
<p>A single-reader multi-case (SRMC) analysis involves a single readers
of multiple cases to compare reader performance metrics across two or
more diagnostic tests. An SRMC analysis can be performed with a call to
<code>srmc()</code>.</p>
<blockquote>
<p><strong>SRMC Function</strong></p>
<p><code>srmc(response, test, case, data, cov = jackknife)</code></p>
<p><em>Description</em></p>
<p>Returns an <code>srmc</code> class object of data that can be used to
estimate and compare reader performance metrics in a single-reader
multi-case statistical analysis.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>response</code>: object defining true case statuses,
corresponding reader ratings, and a reader performance metric to compute
on them.</li>
<li><code>test</code>, <code>case</code>: variables containing the test
and case identifiers for the <code>response</code> observations.</li>
<li><code>data</code>: data frame containing the response and identifier
variables.</li>
<li><code>cov</code>: function <code>jackknife</code>,
<code>unbiased</code>, or <code>DeLong</code> to estimate reader
performance metric covariances.</li>
</ul>
</blockquote>
<p>The function is used similar to <code>mrmc()</code> but without the
<code>reader</code> argument. Below is an example SRMC analysis
performed with one of the readers from the <code>VanDyke</code>
dataset.</p>
<pre class="r"><code>## Subset VanDyke dataset by reader 1
VanDyke1 &lt;- subset(VanDyke, reader == &quot;1&quot;)

## Compare ROC AUC treatment means for reader 1
est &lt;- srmc(binormal_auc(truth, rating), treatment, case, data = VanDyke1)</code></pre>
<details>
<summary>
<strong>Show SRMC Performance Metrics</strong>
</summary>
<pre class="r"><code>print(est)
#&gt; Call:
#&gt; srmc(response = binormal_auc(truth, rating), test = treatment, 
#&gt;     case = case, data = VanDyke1)
#&gt; 
#&gt; Positive truth status: 1 
#&gt; 
#&gt; Response metric data:
#&gt; 
#&gt; # A tibble: 2 × 2
#&gt;       N data$binormal_auc $treatment $reader
#&gt;   &lt;dbl&gt;             &lt;dbl&gt; &lt;fct&gt;      &lt;fct&gt;  
#&gt; 1   114             0.933 1          1      
#&gt; 2   114             0.951 2          1      
#&gt; 
#&gt; ANOVA Table:
#&gt; 
#&gt;                  Df     Sum Sq    Mean Sq
#&gt; treatment         1 0.00010393 0.00010393
#&gt; reader            0 0.00000000 0.00000000
#&gt; treatment:reader  0 0.00000000 0.00000000
#&gt; 
#&gt; 
#&gt; Obuchowski-Rockette error variance and covariance estimates:
#&gt; 
#&gt;           Estimate Correlation
#&gt; Error 0.0008371345          NA
#&gt; Cov1  0.0004275594   0.5107416
#&gt; Cov2  0.0000000000   0.0000000
#&gt; Cov3  0.0000000000   0.0000000</code></pre>
</details>
<details>
<summary>
<strong>Show SRMC ROC Curves</strong>
</summary>
<pre class="r"><code>plot(est)</code></pre>
<img src="using_files/figure-html/unnamed-chunk-24-1.png" width="672" style="display: block; margin: auto;" />
</details>
<details>
<summary>
<strong>Show SRMC ROC Curve Parameters</strong>
</summary>
<pre class="r"><code>print(parameters(est))
#&gt; # A tibble: 2 × 3
#&gt;   Group$reader $treatment     a     b
#&gt;   &lt;fct&gt;        &lt;fct&gt;      &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1 1            1           1.70 0.537
#&gt; 2 1            2           1.85 0.503</code></pre>
</details>
<details>
<summary>
<strong>Show SRMC Test Results</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; Single-Reader Multi-Case Analysis of Variance
#&gt; Data: VanDyke1
#&gt; Factor types: Fixed Readers and Random Cases
#&gt; Covariance method: jackknife
#&gt; 
#&gt; Experimental design: cases nested within reader 
#&gt; 
#&gt; Obuchowski-Rockette variance component and covariance estimates:
#&gt; 
#&gt;           Estimate Correlation
#&gt; Error 0.0008371345          NA
#&gt; Cov1  0.0004275594   0.5107416
#&gt; Cov2  0.0000000000   0.0000000
#&gt; Cov3  0.0000000000   0.0000000
#&gt; 
#&gt; 
#&gt; 95% CIs and tests for treatment binormal_auc pairwise differences:
#&gt;   Comparison    Estimate    StdErr    CI.Lower    CI.Upper         z  p-value
#&gt; 1      1 - 2 -0.01765763 0.0286208 -0.07375337  0.03843810 -0.616951 0.537267
#&gt; 
#&gt; 
#&gt; Single reader 95% CIs:
#&gt;   binormal_auc treatment reader     StdErr  CI.Lower  CI.Upper
#&gt; 1    0.9331609         1      1 0.03348342 0.8675346 0.9987872
#&gt; 2    0.9508186         2      1 0.02351871 0.9047228 0.9969144</code></pre>
</details>
<p>
</div>
<div id="single-test-multi-case-analysis" class="section level1"
number="6">
<h1><span class="header-section-number">6</span> Single-Test Multi-Case
Analysis</h1>
<p>A single-test and single-reader multi-case (STMC) analysis involves a
single reader of multiple cases to estimate a reader performance metric
for one diagnostic test. An STMC analysis can be performed with a call
to <code>stmc()</code>.</p>
<blockquote>
<p><strong>STMC Function</strong></p>
<p><code>stmc(response, case, data, cov = jackknife)</code></p>
<p><em>Description</em></p>
<p>Returns an <code>stmc</code> class object of data that can be used to
estimate a reader performance metric in a single-test and single-reader
multi-case statistical analysis.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>response</code>: object defining true case statuses,
corresponding reader ratings, and a reader performance metric to compute
on them.</li>
<li><code>case</code>: variable containing the case identifiers for the
<code>response</code> observations.</li>
<li><code>data</code>: data frame containing the response and identifier
variables.</li>
<li><code>cov</code>: function <code>jackknife</code>,
<code>unbiased</code>, or <code>DeLong</code> to estimate reader
performance metric covariances.</li>
</ul>
</blockquote>
<p>The function is used similar to <code>mrmc()</code> but without the
<code>test</code> and <code>reader</code> arguments. In the following
example, an STMC analysis is performed with one of the tests and readers
from the <code>VanDyke</code> dataset.</p>
<pre class="r"><code>## Subset VanDyke dataset by treatment 1 and reader 1
VanDyke11 &lt;- subset(VanDyke, treatment == &quot;1&quot; &amp; reader == &quot;1&quot;)

## Estimate ROC AUC for treatment 1 and reader 1
est &lt;- stmc(binormal_auc(truth, rating), case, data = VanDyke11)</code></pre>
<details>
<summary>
<strong>Show STMC ROC Curve</strong>
</summary>
<pre class="r"><code>plot(est)</code></pre>
<img src="using_files/figure-html/unnamed-chunk-27-1.png" width="672" style="display: block; margin: auto;" />
</details>
<details>
<summary>
<strong>Show STMC ROC Curve Parameters</strong>
</summary>
<pre class="r"><code>print(parameters(est))
#&gt; # A tibble: 1 × 2
#&gt;       a     b
#&gt;   &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1  1.70 0.537</code></pre>
</details>
<details>
<summary>
<strong>Show STMC ROC AUC Estimate</strong>
</summary>
<pre class="r"><code>summary(est)
#&gt; binormal_auc       StdErr     CI.Lower     CI.Upper 
#&gt;   0.93316094   0.03348342   0.86753465   0.99878723</code></pre>
</details>
<p>
</div>
<div id="roc-curves" class="section level1" number="7">
<h1><span class="header-section-number">7</span> ROC Curves</h1>
<p>ROC curves can be estimated, summarized, and displayed apart from a
multi-case statistical analysis with the <code>roc_curves()</code>
function. Supported estimation methods include the empirical
distribution (default), binormal model, and binormal likelihood-ratio
model.</p>
<div id="curve-fitting" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Curve Fitting</h2>
<blockquote>
<p><strong>ROC Curves Function</strong></p>
<p><code>roc_curves(truth, rating, groups = list(), method = "empirical")</code></p>
<p><em>Description</em></p>
<p>Returns an <code>roc_curves</code> class object of estimated ROC
curves.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>truth</code>: vector of true binary case statuses, with
positive status taken to be the highest level.</li>
<li><code>rating</code>: numeric vector of case ratings.</li>
<li><code>groups</code> : list or data frame of grouping variables of
the same lengths as <code>truth</code> and <code>rating</code>.</li>
<li><code>method</code>: character string indicating the curve type as
<code>"binormal"</code>, <code>"binormalLR"</code>,
<code>"empirical"</code>, or <code>"trapezoidal"</code>.</li>
</ul>
</blockquote>
<p>A single curve can be estimated over all observations or multiple
curves estimated within the levels of one or more grouping variables.
Examples of both are given in the following sections using variables
from the <code>VanDyke</code> dataset referenced inside of calls to the
<code>with()</code> function. Alternatively, the variables may be
referenced with the <code>$</code> operator; e.g.,
<code>VanDyke$truth</code> and <code>VanDyke$rating</code>. Resulting
curves from <code>roc_curves()</code> can be displayed with the
<code>print()</code> and <code>plot()</code> functions.</p>
<div id="single-curve" class="section level3" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Single Curve</h3>
<pre class="r"><code>## Direct referencing of data frame columns
# curve &lt;- roc_curves(VanDyke$truth, VanDyke$rating)

## Indirect referencing using the with function
curve &lt;- with(VanDyke, {
  roc_curves(truth, rating)
})
plot(curve)</code></pre>
<p><img src="using_files/figure-html/using_curves_one-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="multiple-curves" class="section level3" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Multiple
Curves</h3>
<p>Multiple group-specific curves can be obtained from
<code>roc_curves()</code> by supplying a list or data frame of grouping
variables to the <code>groups</code> argument. Groups will be formed and
displayed in the order in which grouping variables are supplied. For
instance, a second grouping variable will be plotted within the first
one.</p>
<pre class="r"><code>## Grouped by reader
curves &lt;- with(VanDyke, {
  roc_curves(truth, rating,
             groups = list(Reader = reader, Treatment = treatment))
})
plot(curves)</code></pre>
<p><img src="using_files/figure-html/using_curves_reader-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>## Grouped by treatment
curves &lt;- with(VanDyke, {
  roc_curves(truth, rating,
             groups = list(Treatment = treatment, Reader = reader))
})
plot(curves)</code></pre>
<p><img src="using_files/figure-html/using_curves_treatment-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="parametric-curves" class="section level3" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Parametric
Curves</h3>
<p>Estimated parameters for curves obtained with the binormal or
binormal likelihood-ratio models can be extracted as a data frame with
the <code>parameters()</code> function.</p>
<pre class="r"><code>## Binormal curves
curves_binorm &lt;- with(VanDyke, {
  roc_curves(truth, rating,
             groups = list(Treatment = treatment, Reader = reader),
             method = &quot;binormal&quot;)
})
params_binorm &lt;- parameters(curves_binorm)
print(params_binorm)
#&gt; # A tibble: 10 × 3
#&gt;    Group$Treatment $Reader      a     b
#&gt;    &lt;fct&gt;           &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt;
#&gt;  1 1               1         1.70 0.537
#&gt;  2 2               1         1.85 0.503
#&gt;  3 1               2         1.40 0.561
#&gt;  4 2               2         1.66 0.447
#&gt;  5 1               3         1.74 0.635
#&gt;  6 2               3         1.62 0.488
#&gt;  7 1               4         1.93 0.202
#&gt;  8 2               4       Inf    1    
#&gt;  9 1               5         1.06 0.464
#&gt; 10 2               5         1.73 0.422
plot(curves_binorm)</code></pre>
<p><img src="using_files/figure-html/using_curves_binorm-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Estimates for different parameterizations of the binormal
likelihood-ratio model are additionally returned and include those of
the binormal model and the simplification of Pan and Metz <span
class="citation">(1997; Metz and Pan 1999)</span> as well as those of
the bi-chi-squared model <span class="citation">(Hillis
2017)</span>.</p>
<pre class="r"><code>## Binormal likelihood-ratio curves
curves_binormLR &lt;- with(VanDyke, {
  roc_curves(truth, rating,
             groups = list(Treatment = treatment, Reader = reader),
             method = &quot;binormalLR&quot;)
})
params_binormLR &lt;- parameters(curves_binormLR)
print(params_binormLR)
#&gt; # A tibble: 10 × 4
#&gt;    Group$Treatment $Reader   Metz$d_a     $c bichisquared…¹     $theta binorma…²
#&gt;    &lt;fct&gt;           &lt;fct&gt;        &lt;dbl&gt;  &lt;dbl&gt;          &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
#&gt;  1 1               1         2.13     -0.298           3.42   1.71e+ 0   1.71e+0
#&gt;  2 2               1         2.35     -0.321           3.79   1.70e+ 0   1.87e+0
#&gt;  3 1               2         1.73     -0.281           3.17   1.32e+ 0   1.40e+0
#&gt;  4 2               2         0.00700  -0.791          73.3    3.48e- 7   4.99e-3
#&gt;  5 1               3         0.0140   -0.746          47.0    2.22e- 6   9.99e-3
#&gt;  6 2               3         2.08     -0.330           3.94   1.23e+ 0   1.65e+0
#&gt;  7 1               4         0.000417 -0.932         797.     1.09e-10   2.95e-4
#&gt;  8 2               4       Inf         0               1    Inf        Inf      
#&gt;  9 1               5         0.895    -0.508           9.37   5.94e- 2   6.66e-1
#&gt; 10 2               5         2.02     -0.553          12.1    2.18e- 1   1.49e+0
#&gt; # … with 1 more variable: binormal$b &lt;dbl&gt;, and abbreviated variable names
#&gt; #   ¹​bichisquared$lambda, ²​binormal$a
plot(curves_binormLR)</code></pre>
<p><img src="using_files/figure-html/using_curves_binormLR-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="curve-points" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Curve Points</h2>
<p>Points on an ROC curve estimated with <code>roc_curves()</code> can
be extracted with the <code>points()</code> function. True positive
rates (TPRs) and false positive rates (FPRs) on the estimated curve are
returned for a given set of sensitivity or specificity values or, in the
case of empirical curves, the original points. ROC curve points can be
displayed with <code>print()</code> and <code>plot()</code>.</p>
<blockquote>
<p><strong>ROC Points Function</strong></p>
<p><code>## Method for class 'roc_curves'</code><br />
<code>points(x, metric = "specificity", values = seq(0, 1, length = 101), ...)</code></p>
<p><code>## Method for class 'empirical_curves'</code><br />
<code>points(x, metric = "specificity", values = NULL, which = "curve", ...)</code></p>
<p><em>Description</em></p>
<p>Returns an <code>roc_points</code> class object that is a data frame
of false positive and true positive rates from an estimated ROC
curve.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>x</code>: object from <code>roc_curves()</code> for which to
compute points on the curves.</li>
<li><code>metric</code>: character string specifying
<code>"specificity"</code> or <code>"sensitivity"</code> as the reader
performance metric to which <code>values</code> correspond.</li>
<li><code>values</code>: numeric vector of values at which to compute
ROC curve points, or <code>NULL</code> for default empirical values as
determined by <code>which</code>.</li>
<li><code>which</code>: character string indicating whether to use
curve-specific observed values and 0 and 1 (<code>"curve"</code>), the
combination of these values over all curves (<code>"curves"</code>), or
only the observed curve-specific values (<code>"observed"</code>).</li>
</ul>
</blockquote>
<pre class="r"><code>## Extract points at given specificities
curve_spec_pts &lt;- points(curves, metric = &quot;spec&quot;, values = c(0.5, 0.7, 0.9))
print(curve_spec_pts)
#&gt; # A tibble: 30 × 3
#&gt;    Group$Treatment $Reader   FPR   TPR
#&gt;  * &lt;fct&gt;           &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt;
#&gt;  1 1               1         0.1 0.862
#&gt;  2 1               1         0.3 0.908
#&gt;  3 1               1         0.5 0.935
#&gt;  4 2               1         0.1 0.843
#&gt;  5 2               1         0.3 0.966
#&gt;  6 2               1         0.5 0.978
#&gt;  7 1               2         0.1 0.747
#&gt;  8 1               2         0.3 0.821
#&gt;  9 1               2         0.5 0.872
#&gt; 10 2               2         0.1 0.821
#&gt; # … with 20 more rows
plot(curve_spec_pts, coord_fixed = FALSE)</code></pre>
<p><img src="using_files/figure-html/using_curves_points-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>
## Extract points at given sensitivities
curve_sens_pts &lt;- points(curves, metric = &quot;sens&quot;, values = c(0.5, 0.7, 0.9))
print(curve_sens_pts)
#&gt; # A tibble: 30 × 3
#&gt;    Group$Treatment $Reader    FPR   TPR
#&gt;  * &lt;fct&gt;           &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt;
#&gt;  1 1               1       0.0116   0.5
#&gt;  2 1               1       0.0246   0.7
#&gt;  3 1               1       0.254    0.9
#&gt;  4 2               1       0        0.5
#&gt;  5 2               1       0        0.7
#&gt;  6 2               1       0.337    0.9
#&gt;  7 1               2       0.0130   0.5
#&gt;  8 1               2       0.0543   0.7
#&gt;  9 1               2       0.609    0.9
#&gt; 10 2               2       0        0.5
#&gt; # … with 20 more rows
plot(curve_sens_pts, coord_fixed = FALSE)</code></pre>
<p><img src="using_files/figure-html/using_curves_points-2.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="mean-curves" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Mean Curves</h2>
<p>A mean ROC curve from multiple group-specific curves returned by
<code>roc_curves()</code> can be computed with the <code>means()</code>
function. Curves can be averaged over sensitivities, specificities, or
binormal parameters <span class="citation">(Chen and Samuelson
2014)</span>. Averaged curves can be displayed with <code>print()</code>
and <code>plot()</code>.</p>
<blockquote>
<p><strong>ROC Means Function</strong></p>
<p><code>## Method for class 'roc_curves'</code><br />
<code>mean(x, ...)</code></p>
<p><code>## Method for class 'binormal_curves'</code><br />
<code>mean(x, method = "points", ...)</code></p>
<p><em>Description</em></p>
<p>Returns an <code>roc_points</code> class object.</p>
<p><em>Arguments</em></p>
<ul>
<li><code>x</code>: object from <code>roc_curves()</code> for which to
average over the curves.</li>
<li><code>method</code>: character string indicating whether to average
binormal curves over <code>"points"</code> or
<code>"parameters"</code>.</li>
<li><code>...</code>: optional arguments passed to
<code>points()</code>, including at which <code>metric</code>
(<code>"sensitivity"</code> or <code>"specificity"</code>) values to
average points on the ROC curves.</li>
</ul>
</blockquote>
<pre class="r"><code>## Average sensitivities at given specificities (default)
curves_mean &lt;- mean(curves)
print(curves_mean)
#&gt; # A tibble: 20 × 2
#&gt;       FPR   TPR
#&gt;  *  &lt;dbl&gt; &lt;dbl&gt;
#&gt;  1 0      0    
#&gt;  2 0      0.402
#&gt;  3 0.0145 0.686
#&gt;  4 0.0290 0.762
#&gt;  5 0.0435 0.790
#&gt;  6 0.0580 0.802
#&gt;  7 0.0725 0.813
#&gt;  8 0.101  0.835
#&gt;  9 0.116  0.844
#&gt; 10 0.130  0.852
#&gt; 11 0.159  0.862
#&gt; 12 0.188  0.872
#&gt; 13 0.319  0.904
#&gt; 14 0.362  0.912
#&gt; 15 0.435  0.925
#&gt; 16 0.638  0.956
#&gt; 17 0.667  0.961
#&gt; 18 0.696  0.966
#&gt; 19 0.913  0.992
#&gt; 20 1      1
plot(curves_mean)</code></pre>
<p><img src="using_files/figure-html/using_curves_mean_spec-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>## Average specificities at given sensitivities
curves_mean &lt;- mean(curves, metric = &quot;sens&quot;)
print(curves_mean)
#&gt; # A tibble: 23 × 2
#&gt;        FPR   TPR
#&gt;  *   &lt;dbl&gt; &lt;dbl&gt;
#&gt;  1 0       0    
#&gt;  2 0.00698 0.511
#&gt;  3 0.00804 0.556
#&gt;  4 0.00899 0.578
#&gt;  5 0.00995 0.6  
#&gt;  6 0.0109  0.622
#&gt;  7 0.0214  0.667
#&gt;  8 0.0280  0.689
#&gt;  9 0.0358  0.711
#&gt; 10 0.0450  0.733
#&gt; # … with 13 more rows
plot(curves_mean)</code></pre>
<p><img src="using_files/figure-html/using_curves_mean_sens-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="reader-performance-metrics" class="section level1" number="8">
<h1><span class="header-section-number">8</span> Reader Performance
Metrics</h1>
<p>The reader performance metrics described previously for use with
<code>mrmc()</code> and related functions to analyze multi and
single-reader multi-case studies can be applied to truth and rating
vectors as stand-alone functions. This enables estimation of performance
metrics for other applications, such as predictive modeling, that may be
of interest.</p>
<div id="roc-curve-metrics" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> ROC Curve
Metrics</h2>
<p>AUC, partial AUC, sensitivity, and specificity are estimated below
with an empirical ROC curve. Estimates with binormal and binormal
likelihood-ratio curves can be obtained by replacing
<code>empirical</code> in the function names with <code>binormal</code>
and <code>binormalLR</code>, respectively.</p>
<pre class="r"><code>## Total area under the empirical ROC curve
empirical_auc(VanDyke$truth, VanDyke$rating)
#&gt; [1] 0.9229791

## Partial area for specificity from 0.7 to 1.0
empirical_auc(VanDyke$truth, VanDyke$rating, partial = &quot;spec&quot;, min = 0.70, max = 1.0)
#&gt; [1] 0.2499923

## Partial area for sensitivity from 0.7 to 1.0
empirical_auc(VanDyke$truth, VanDyke$rating, partial = &quot;sens&quot;, min = 0.70, max = 1.0)
#&gt; [1] 0.2262129

## Sensitivity for given specificity
empirical_sens(VanDyke$truth, VanDyke$rating, spec = 0.8)
#&gt; [1] 0.8812346

## Sensitivity for given specificity
empirical_spec(VanDyke$truth, VanDyke$rating, sens = 0.8)
#&gt; [1] 0.94434</code></pre>
</div>
<div id="binary-metrics-1" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> Binary Metrics</h2>
<p>Sensitivity and specificity for binary ratings are available with the
<code>binary_sens()</code> and <code>binary_spec()</code> functions as
demonstrated in the next example based on a binary rating created from
the numeric one in the <code>VanDyke</code> dataset.</p>
<pre class="r"><code>## Create binary classification
VanDyke$binary_rating &lt;- VanDyke$rating &gt;= 3

## Sensitivity
binary_sens(VanDyke$truth, VanDyke$binary_rating)
#&gt; [1] 0.8711111

## Specificity
binary_spec(VanDyke$truth, VanDyke$binary_rating)
#&gt; [1] 0.8478261</code></pre>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Abbey:2013:SPC" class="csl-entry">
Abbey, Craig K, Frank W Samuelson, and Brandon D Gallas. 2013.
<span>“Statistical Power Considerations for a Utility Endpoint in
Observer Performance Studies.”</span> <em>Academic Radiology</em> 207:
798–806.
</div>
<div id="ref-Chen:2014:ARO" class="csl-entry">
Chen, W, and Frank W Samuelson. 2014. <span>“The Average Receiver
Operating Characteristic Curve in Multireader Multicase Imaging
Studies.”</span> <em>The British Journal of Radiology</em> 87: 20140016.
</div>
<div id="ref-DeLong:1988:CAU" class="csl-entry">
DeLong, E R, D M DeLong, and D L Clarke-Pearson. 1988. <span>“Comparing
the Areas Under Two or More Correlated Receiver Operating Characteristic
Curves: A Nonparametric Approach.”</span> <em>Biometrics</em> 44:
837–45.
</div>
<div id="ref-Dorfman:1992:ROC" class="csl-entry">
Dorfman, D D, K S Berbaum, and C E Metz. 1992. <span>“Receiver Operating
Characteristic Rating Analysis. <span>Generalization</span> to the
Population of Readers and Patients with the Jackknife Method.”</span>
<em>Investigative Radiology</em> 27: 723–31.
</div>
<div id="ref-Efron:1982:JBR" class="csl-entry">
Efron, Bradley. 1982. <em>The Jackknife, the Bootstrap and Other
Resampling Plans</em>. Philadelphia: SIAM.
</div>
<div id="ref-Gallas:2007:MMV" class="csl-entry">
Gallas, B D, G A Pennello, and K J Meyers. 2007. <span>“Multireader
Multicase Variance Analysis for Binary Data.”</span> <em>Journal of the
Optical Society of America A</em> 24: B70–80.
</div>
<div id="ref-Hillis:2007:CDD" class="csl-entry">
Hillis, S L. 2007. <span>“A Comparison of Denominator Degrees of Freedom
Methods for Multiple Observer <span>ROC</span> Analysis.”</span>
<em>Statistics in Medicine</em> 26: 596–619.
</div>
<div id="ref-Hillis:2014:MMA" class="csl-entry">
———. 2014. <span>“A Marginal-Mean <span>ANOVA</span> Approach for
Analyzing Mulitreader Multicase Radiological Imaging Data.”</span>
<em>Statistics in Medicine</em> 33: 330–60.
</div>
<div id="ref-Hillis:2017:EBL" class="csl-entry">
———. 2017. <span>“Equivalence of Binormal Likelihood-Ratio and
Bi-Chi-Squared ROC Curve Models.”</span> <em>Statistics in Medicine</em>
35: 2031–57.
</div>
<div id="ref-Hillis:2018:RRM" class="csl-entry">
———. 2018. <span>“Relationship Between <span>Roe</span> and
<span>Metz</span> Simulation Model for Multireader Diagnostic Data and
<span>Obuchowski-Rockette</span> Model Parameters.”</span>
<em>Statistics in Medicine</em> 37: 2067–93.
</div>
<div id="ref-Hillis:2008:RDD" class="csl-entry">
Hillis, S L, K S Berbaum, and C E Metz. 2008. <span>“Recent Developments
in the <span>Dorfman-Berbaum-Metz</span> Procedure for Multireader
<span>ROC</span> Study Analysis.”</span> <em>Academic Radiology</em> 15:
647–61.
</div>
<div id="ref-Hillis:2005:CDB" class="csl-entry">
Hillis, S L, N A Obuchowski, K M Schartz, and K S Berbaum. 2005.
<span>“A Comparison of the <span>Dorfman-Berbaum-Metz</span> and
<span>Obuchowski-Rockette</span> Methods for Receiver Operating
Characteristic <span>(ROC)</span> Data.”</span> <em>Statistics in
Medicine</em> 24: 1579–1607.
</div>
<div id="ref-Metz:1993:PBR" class="csl-entry">
Metz, Charles E, and Xiaochuan Pan. 1999. <span>“"Proper" Binormal
<span>ROC</span> Curves: Theory and Maximum-Likelihood
Estimation.”</span> <em>Journal of Mathematical Psychology</em> 43:
1–33.
</div>
<div id="ref-Obuchowski:1995:HTD" class="csl-entry">
Obuchowski, N A, and H E Rockette. 1995. <span>“Hypothesis Testing of
Diagnostic Accuracy for Multiple Readers and Multiple Tests: An
<span>ANOVA</span> Approach with Dependent Observations.”</span>
<em>Communications in Statistics–Simulation and Computation</em> 24:
285–308.
</div>
<div id="ref-Pan:1997:PBM" class="csl-entry">
Pan, Xiaochuan, and Charles E Metz. 1997. <span>“The "Proper" Binormal
Model: Parametric Receiver Operating Characteristic Curve Estimation
with Degenerate Data.”</span> <em>Statistics in Radiology</em> 4:
380–89.
</div>
<div id="ref-MRMCaov-SPIE2020" class="csl-entry">
Smith, Brian J., and Stephen L. Hillis. 2020. <span>“Multi-Reader
Multi-Case Analysis of Variance Software for Diagnostic Performance
Comparison of Imaging Modalities.”</span> In <em>Proceedings of SPIE
11316, Medical Imaging 2020: Image Perception, Observer Performance, and
Technology Assessment</em>, edited by Frank Samuelson and Sian
Taylor-Phillips, 113160K. <a
href="https://doi.org/10.117/12.2549075">https://doi.org/10.117/12.2549075</a>.
</div>
<div id="ref-MRMCaov-package" class="csl-entry">
Smith, Brian J, Stephen L Hillis, and Lorenzo L Pesce. 2022.
<em><span>MCMCaov</span>: Multi-Reader Multi-Case Analysis of
Variance</em>. <a
href="https://github.com/brian-j-smith/MRMCaov">https://github.com/brian-j-smith/MRMCaov</a>.
</div>
<div id="ref-VanDyke:1993:CMD" class="csl-entry">
VanDyke, C W, R D White, N A Obuchowski, M A Geisinger, R J Lorig, and M
A Meziane. 1993. <span>“Cine <span>MRI</span> in the Diagnosis of
Thoracic Aortic Dissection.”</span> Chicago, IL.
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
