---
title: MRMCaov for R User Guide
subtitle: Package Version `r packageVersion("MRMCaov")`
output:
  pdf_document:
    toc: true
    number_sections: yes
author:
- Brian J Smith, Department of Biostatistics, University of Iowa
- Stephen L Hillis, Departments of Radiology and Biostatistics, University of Iowa
date: "`r Sys.Date()`"
bibliography: ../src/bibliography.bib
nocite: |
  @MRMCaov-package, @MRMCaov-SPIE2020
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = TRUE,
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 4,
  fig.align = "center"
)

print_data <- function(x) {
  res <- head(x, n = 20)
  print(res)
  nmore <- nrow(x) - nrow(res)
  if (nmore) cat("... with", nmore, "more rows\n")
}
```

```{r child = "../src/overview.Rmd"}
```

```{r child = "../src/using_intro.Rmd"}
```

```{r child = "../src/using_model.Rmd"}
```

```{r child = "../src/using_example.Rmd"}
```

```{r child = "../src/using_mrmc.Rmd"}
```

```{r child = "../src/using_srmc.Rmd"}
```

```{r child = "../src/using_stmc.Rmd"}
```

```{r child = "../src/using_curves.Rmd"}
```

```{r child = "../src/using_metrics.Rmd"}
```


# References
