# Introduction

A common study design for comparing the diagnostic performance of imaging modalities, or diagnostic tests, is to obtain modality-specific ratings from multiple readers of multiple cases (MRMC) whose true statuses are known.  In such a design, receiver operating characteristic (ROC) metrics, such as area under the ROC curve (ROC AUC), can be used to quantify correspondence between reader ratings and case status.  Metrics can then be compared statistically to determine if modalities differ.  However, special statistical methods are needed when readers or cases represent a random sample from a larger population of interest and there is overlap between modalities, readers, and/or cases.  An ANOVA model designed for these characteristics of MRMC studies was initially proposed by Dorfman et al. [@Dorfman:1992:ROC] and Obuchowski and Rockette [@Obuchowski:1995:HTD] and later unified and improved by Hillis and colleagues [@Hillis:2005:CDB; @Hillis:2007:CDD; @Hillis:2008:RDD; @Hillis:2018:RRM].  This paper describes the implementation of their models in the \pkg{MRMCaov} \proglang{R} package [@MRMCaov-package].

Several other \proglang{R} packages allow for the estimation and comparison of certain ROC metrics and MRMC study designs.  \pkg{pROC} provides general tools for the estimation, visualization, and comparison of ROC AUC and sensitivity/specificity at a given specificity/sensitivity [@Robin:2011:pROC].  The package can be used to compare these metrics across two diagnostic tests in MRMC study designs where one reader rates the same (paired) or different (unpaired) sets of cases.  \pkg{iMRMC} is specifically designed to compare ROC AUC, sensitivity, and specificity in MRMC studies of two or more diagnostic tests [@Gallas:2022:iMRMC].  Arbitrary study designs are supported in which one or more readers provide ratings that are paired, unpaired, or partially paired (some combination thereof).  The package is based on a U-statistics approach to estimating the metrics and their covariances.  \pkg{RJafroc} enables analysis of ROC free-response receiver operating characteristic (FROC) curves across one or more diagnostic tests in MRMC studies, and \pkg{BayesianFROC} is a Bayesian implementation of FROC methods.

* Statistical comparisons of diagnostic tests with respect to reader performance metrics
* Comparisons based on the ANOVA model of Obuchowski-Rockette and the unified framework of Hillis
* Reader performance metrics for area under receiver operating characteristic curves (ROC AUCs), partial AUCs, expected utility of ROC curves, likelihood ratio of positive or negative tests, sensitivity, specificity, and user-defined metrics
* Parametric and nonparametric estimation and plotting of ROC curves
* Support for factorial, nested, and partially paired study designs
* Inference for random or fixed readers and cases
* Conversion of Obuchowski-Rockette to Roe, Metz & Hillis model parameters and vice versa
* DeLong, jackknife, and unbiased covariance estimation
